In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

# Bảng 1. sinhvien.xlsx

### Xử lí chung

In [2]:
# Đọc dữ liệu
df1 = pd.read_excel("Education_dataset_V2/01.sinhvien.xlsx")
df1.head()

,id,mssv,namsinh,gioitinh,noisinh,lopsh,khoa,hedt,khoahoc,chuyennganh2,...,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56
0,1.0,BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2,1995.0,1.0,TP. Hồ Chí Minh,KTPM0001,CNPM,CQUI,8.0,D480103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,2420ED57XPvAibaEXe/Lh6v1XxTKJa6JLFRUPkLM,1995.0,1.0,Đồng Tháp,HTTT0001,HTTT,CTTT,8.0,D480104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,83B76C01XPvAibaEXe/lOccskaOiO2K46r7t4qnt,1994.0,1.0,Hà Nam Ninh,KHMT2013,KHMT,CQUI,8.0,D480101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,91F785ABXPvAibaEXe/lOccskaOiO5y4GbVvuRQu,1995.0,1.0,TP. Hồ Chí Minh,HTTT0001,HTTT,CTTT,8.0,D480104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,007C275DXPvAibaEXe+TFgEDwYNnveOOmOYeYzF6,1995.0,1.0,Thành phố Hồ Chí Minh,MMTT0001,MMT&TT,CQUI,8.0,D480201,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
# In ra số dòng, số cột của bảng
df1.shape

(8316, 69)

In [43]:
# In ra các cột của bảng
df1.columns

Index(['id', 'mssv', ' namsinh', ' gioitinh', ' noisinh', ' lopsh', ' khoa',
       ' hedt', ' khoahoc', ' chuyennganh2', ' tinhtrang', ' diachi_tinhtp',
       'Column1', '_1', '_2', '_3', '_4', '_5', '_6', '_7', '_8', '_9', '_10',
       '_11', '_12', '_13', '_14', '_15', '_16', '_17', '_18', '_19', '_20',
       '_21', '_22', '_23', '_24', '_25', '_26', '_27', '_28', '_29', '_30',
       '_31', '_32', '_33', '_34', '_35', '_36', '_37', '_38', '_39', '_40',
       '_41', '_42', '_43', '_44', '_45', '_46', '_47', '_48', '_49', '_50',
       '_51', '_52', '_53', '_54', '_55', '_56'],
      dtype='object')

In [44]:
# Bỏ các cột bắt đầu bằng kí tự "_"
df1 = df1.drop(df1.columns[df1.columns.str.startswith('_')], axis=1)
df1.columns

Index(['id', 'mssv', ' namsinh', ' gioitinh', ' noisinh', ' lopsh', ' khoa',
       ' hedt', ' khoahoc', ' chuyennganh2', ' tinhtrang', ' diachi_tinhtp',
       'Column1'],
      dtype='object')

In [45]:
# Bỏ khoảng trắng ở tên cột
df1.columns = df1.columns.str.strip()
df1.columns

Index(['id', 'mssv', 'namsinh', 'gioitinh', 'noisinh', 'lopsh', 'khoa', 'hedt',
       'khoahoc', 'chuyennganh2', 'tinhtrang', 'diachi_tinhtp', 'Column1'],
      dtype='object')

In [46]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8316 entries, 0 to 8315
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             8295 non-null   float64
 1   mssv           8295 non-null   object
 2   namsinh        8294 non-null   float64
 3   gioitinh       8295 non-null   float64
 4   noisinh        8295 non-null   object
 5   lopsh          8295 non-null   object
 6   khoa           8295 non-null   object
 7   hedt           8295 non-null   object
 8   khoahoc        8295 non-null   float64
 9   chuyennganh2   8295 non-null   object
 10  tinhtrang      8295 non-null   float64
 11  diachi_tinhtp  8295 non-null   object
 12  Column1        1549 non-null   object
dtypes: float64(5), object(8)
memory usage: 844.7+ KB

In [47]:
# Thống kê giá trị NaN ở mỗi cột
df1.isna().sum()

id                 21
mssv               21
namsinh            22
gioitinh           21
noisinh            21
lopsh              21
khoa               21
hedt               21
khoahoc            21
chuyennganh2       21
tinhtrang          21
diachi_tinhtp      21
Column1          6767
dtype: int64

In [48]:
# Cột Column1 có nhiều giá trị NaN
print("Số lượng giá trị khác NaN trong cột NaN:", 
      len(df1['Column1'][df1['Column1'].notna()].unique()))
df1['Column1'][df1['Column1'].notna()].unique()

Số lượng giá trị khác NaN trong cột NaN: 1179

array([' Tp. Cần Thơ', ' Lâm Đồng.', 'Tổ 12', ..., " tỉnh Vĩnh Long '",
       ' phường Mỹ Hòa', ' xã cư an '], dtype=object)

In [49]:
# Bỏ cột Column1 vì có nhiều giá trị NaN
df1.drop(columns = "Column1", inplace=True)
df1.head()

,id,mssv,namsinh,gioitinh,noisinh,lopsh,khoa,hedt,khoahoc,chuyennganh2,tinhtrang,diachi_tinhtp
0,1.0,BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2,1995.0,1.0,TP. Hồ Chí Minh,KTPM0001,CNPM,CQUI,8.0,D480103,3.0,Thành phố Hồ Chí Minh
1,2.0,2420ED57XPvAibaEXe/Lh6v1XxTKJa6JLFRUPkLM,1995.0,1.0,Đồng Tháp,HTTT0001,HTTT,CTTT,8.0,D480104,3.0,Huyện Hóc Môn
2,3.0,83B76C01XPvAibaEXe/lOccskaOiO2K46r7t4qnt,1994.0,1.0,Hà Nam Ninh,KHMT2013,KHMT,CQUI,8.0,D480101,5.0,Tỉnh Hà Nam
3,4.0,91F785ABXPvAibaEXe/lOccskaOiO5y4GbVvuRQu,1995.0,1.0,TP. Hồ Chí Minh,HTTT0001,HTTT,CTTT,8.0,D480104,3.0,Thành phố Hồ Chí Minh
4,5.0,007C275DXPvAibaEXe+TFgEDwYNnveOOmOYeYzF6,1995.0,1.0,Thành phố Hồ Chí Minh,MMTT0001,MMT&TT,CQUI,8.0,D480201,8.0,Thành phố Hồ Chí Minh

In [50]:
# Thống kê giá trị NaN ở mỗi cột
df1.isna().sum()

id               21
mssv             21
namsinh          22
gioitinh         21
noisinh          21
lopsh            21
khoa             21
hedt             21
khoahoc          21
chuyennganh2     21
tinhtrang        21
diachi_tinhtp    21
dtype: int64

In [51]:
# Loại bỏ giá trị NaN ở tất cả các cột
df1.dropna(inplace=True)
df1.shape

(8294, 12)

In [52]:
df1.isna().sum()

id               0
mssv             0
namsinh          0
gioitinh         0
noisinh          0
lopsh            0
khoa             0
hedt             0
khoahoc          0
chuyennganh2     0
tinhtrang        0
diachi_tinhtp    0
dtype: int64

### noisinh

In [53]:
# Loại bỏ kí tự ' ở 2 đầu giá trị (thay thế ' bằng kí tự rỗng)
df1['noisinh'] = df1['noisinh'].str.replace("'", '', regex=True)
df1["noisinh"].unique()

array([' TP. Hồ Chí Minh', ' Đồng Tháp', ' Hà Nam Ninh',
       ' Thành phố Hồ Chí Minh', ' Hà Tĩnh', ' Thanh Hóa', ' Quảng Ngãi',
       ' Khánh Hoà', ' Cần Thơ', ' Gia Lai', ' Tiền Giang', ' Vĩnh Long',
       ' Sông Bé', ' Kiên Giang', ' Lâm Đồng', ' Hải Dương', ' Trà Vinh',
       ' Nam Định', ' Quảng Nam', ' Bình Thuận', ' Quảng Bình',
       ' Bến Tre', ' Ninh Thuận', ' Bình Định', ' An Giang',
       ' Bà Rịa - Vũng Tàu', ' Thừa Thiên Huế', ' Kon Tum', ' Tây Ninh',
       ' Hà Nội', ' Đồng Nai', ' Thanh Hoá', ' Nghệ An', ' NULL',
       ' Phú Yên', ' Đăk Lăk', ' Tp Hồ Chí Minh', ' Đắc Nông',
       ' Bình Dương', ' Khánh Hòa', ' Long An', ' Thái Bình',
       ' Bình Phước', ' Hà Sơn Bình', ' Đà Nẵng', ' Ninh Bình', ' Cà Mau',
       ' Quảng Trị', ' Hải Hưng', ' Hưng Yên', ' Hà Tây',
       ' Thành phố Cần Thơ', ' Đắk Lắk', ' Tỉnh Đồng Nai', ' Đắk Nông',
       ' Bắc Giang', ' Thành phố Đà Nẵng', ' Hải Phòng',
       ' Tỉnh Bình Dương', ' Minh Hải', ' Sóc Trăng', ' Hà Nam',
       ' Hậu Giang', ' Bắc Cạn', ' Vĩnh Phúc', ' Bạc Liêu',
       ' Tỉnh Tây Ninh', ' Campuchia', ' Bắc Ninh', ' Hồ Chí Minh City',
       ' Liên Bang Nga', ' Tp. Nha Trang', ' Thành phố Hà Nội',
       ' Nghĩa Sơn - Nghĩa Hưng - Nam Định', ' KonTum', ' Bình Định',
       ' Quảng Ninh', ' Phú Thọ', ' Tp.Hồ Chí Minh', ' Lạng Sơn',
       ' Bình Dương', ' Cộng hoà Séc', ' Yên Bái', ' ',
       ' Tp. Hồ Chí Minh', ' Tỉnh Đăklăk', ' Thái Bình', ' Tiền giang',
       ' ĐăkLăk', ' Tp.Cần Thơ', ' Quảng Nam', ' Nghệ an',
       ' Đồng Tháp', ' Đăk Nông', ' Gia lai', ' Quãng Ngãi', ' Nghệ an',
       ' Đà Lạt', ' Lâm Đồng', ' Thành phố Hải Phòng', ' Nghệ An',
       ' nam định', ' Hà Tĩnh', ' phú yên', ' Tỉnh Ninh Thuận',
       ' Đồng Nai', ' đồng nai', ' Bình Phước ', ' Tỉnh Thanh Hóa',
       ' TP.HỒ CHÍ MINH', ' Thành Phố Hồ Chí Minh', ' Cao Bằng',
       ' Thành phố Hồ Chí Minh', ' Hà Tĩnh ', ' Đăk lăk', ' Trà vinh',
       ' Nghệ An ', ' Nam Định', ' Bình Thuận ', ' Bà Rịa Vũng Tàu',
       ' Đồng Tháp ', ' Tp.Hồ Chí Minh', ' Tiền Giang ',
       ' Tp.Hải Phòng', ' Bình Thuận', ' Sóc Trăng', ' Tỉnh Nghệ An',
       ' Bình Định ', ' Tiền Giang', ' Ninh Thuận ', ' Hà tĩnh',
       ' Quảng Ngãi', ' Bà Rịa-Vũng Tàu', ' Kontum', ' Quảng Trị',
       ' Tp. Vũng Tàu', ' Bến Tre', ' Tỉnh Khánh Hòa', ' TP Hồ Chí Minh',
       ' TP.Hồ Chí Minh', ' Hà Nam ', ' Australia', ' Vĩnh Long',
       ' Quảng BÌnh', ' Sóc Trăng ', ' Hòa Bình', ' Phú Yên ',
       ' Bình phước ', ' TP.Hà Nội', ' Quảng Nam ', ' hà tĩnh ',
       ' Bình ĐỊnh', ' Bạc Liêu', ' Bạc liêu', ' Hồ Chí Minh',
       ' Đồng tháp', ' Vũng Tàu', ' Lai Châu', ' Bình phước', ' Phú yên',
       ' An giang', ' thành phố hồ chí minh', ' bình thuận',
       ' TP. Buôn Ma Thuột', ' Phú Yên', ' Quảng Trị ', ' Khánh Hòa',
       ' thành phố Hồ Chí Minh', ' Tuyên Quang', ' Thái Nguyên',
       ' Quận Thủ Đức', ' TP. HỒ CHÍ MINH', ' LONG HỒ'], dtype=object)

In [54]:
# Định dạng in hoa ở mỗi kí tự đầu tiên
df1['noisinh'] = df1['noisinh'].str.lower()
df1["noisinh"].unique()

array([' tp. hồ chí minh', ' đồng tháp', ' hà nam ninh',
       ' thành phố hồ chí minh', ' hà tĩnh', ' thanh hóa', ' quảng ngãi',
       ' khánh hoà', ' cần thơ', ' gia lai', ' tiền giang', ' vĩnh long',
       ' sông bé', ' kiên giang', ' lâm đồng', ' hải dương', ' trà vinh',
       ' nam định', ' quảng nam', ' bình thuận', ' quảng bình',
       ' bến tre', ' ninh thuận', ' bình định', ' an giang',
       ' bà rịa - vũng tàu', ' thừa thiên huế', ' kon tum', ' tây ninh',
       ' hà nội', ' đồng nai', ' thanh hoá', ' nghệ an', ' null',
       ' phú yên', ' đăk lăk', ' tp hồ chí minh', ' đắc nông',
       ' bình dương', ' khánh hòa', ' long an', ' thái bình',
       ' bình phước', ' hà sơn bình', ' đà nẵng', ' ninh bình', ' cà mau',
       ' quảng trị', ' hải hưng', ' hưng yên', ' hà tây',
       ' thành phố cần thơ', ' đắk lắk', ' tỉnh đồng nai', ' đắk nông',
       ' bắc giang', ' thành phố đà nẵng', ' hải phòng',
       ' tỉnh bình dương', ' minh hải', ' sóc trăng', ' hà nam',
       ' hậu giang', ' bắc cạn', ' vĩnh phúc', ' bạc liêu',
       ' tỉnh tây ninh', ' campuchia', ' bắc ninh', ' hồ chí minh city',
       ' liên bang nga', ' tp. nha trang', ' thành phố hà nội',
       ' nghĩa sơn - nghĩa hưng - nam định', ' kontum', ' bình định',
       ' quảng ninh', ' phú thọ', ' tp.hồ chí minh', ' lạng sơn',
       ' bình dương', ' cộng hoà séc', ' yên bái', ' ', ' tỉnh đăklăk',
       ' thái bình', ' đăklăk', ' tp.cần thơ', ' quảng nam',
       ' nghệ an', ' đồng tháp', ' đăk nông', ' quãng ngãi', ' đà lạt',
       ' lâm đồng', ' thành phố hải phòng', ' hà tĩnh', ' phú yên',
       ' tỉnh ninh thuận', ' đồng nai', ' bình phước ',
       ' tỉnh thanh hóa', ' cao bằng', ' thành phố hồ chí minh',
       ' hà tĩnh ', ' nghệ an ', ' nam định', ' bình thuận ',
       ' bà rịa vũng tàu', ' đồng tháp ', ' tp.hồ chí minh',
       ' tiền giang ', ' tp.hải phòng', ' bình thuận', ' sóc trăng',
       ' tỉnh nghệ an', ' bình định ', ' tiền giang', ' ninh thuận ',
       ' quảng ngãi', ' bà rịa-vũng tàu', ' quảng trị',
       ' tp. vũng tàu', ' bến tre', ' tỉnh khánh hòa', ' hà nam ',
       ' australia', ' vĩnh long', ' sóc trăng ', ' hòa bình',
       ' phú yên ', ' tp.hà nội', ' quảng nam ', ' bạc liêu',
       ' hồ chí minh', ' vũng tàu', ' lai châu', ' tp. buôn ma thuột',
       ' quảng trị ', ' khánh hòa', ' tuyên quang', ' thái nguyên',
       ' quận thủ đức', ' long hồ'], dtype=object)

In [55]:
# Loại bỏ kí tự tp. ở đầu giá trị (thay thế tp. bằng kí tự rỗng)
df1['noisinh'] = df1['noisinh'].str.replace("tp.", '', regex=True)
df1['noisinh'] = df1['noisinh'].str.replace("thành phố.", '', regex=True)
df1["noisinh"].unique()

array(['  hồ chí minh', ' đồng tháp', ' hà nam ninh', ' hồ chí minh',
       ' hà tĩnh', ' thanh hóa', ' quảng ngãi', ' khánh hoà', ' cần thơ',
       ' gia lai', ' tiền giang', ' vĩnh long', ' sông bé', ' kiên giang',
       ' lâm đồng', ' hải dương', ' trà vinh', ' nam định', ' quảng nam',
       ' bình thuận', ' quảng bình', ' bến tre', ' ninh thuận',
       ' bình định', ' an giang', ' bà rịa - vũng tàu', ' thừa thiên huế',
       ' kon tum', ' tây ninh', ' hà nội', ' đồng nai', ' thanh hoá',
       ' nghệ an', ' null', ' phú yên', ' đăk lăk', ' đắc nông',
       ' bình dương', ' khánh hòa', ' long an', ' thái bình',
       ' bình phước', ' hà sơn bình', ' đà nẵng', ' ninh bình', ' cà mau',
       ' quảng trị', ' hải hưng', ' hưng yên', ' hà tây', ' đắk lắk',
       ' tỉnh đồng nai', ' đắk nông', ' bắc giang', ' hải phòng',
       ' tỉnh bình dương', ' minh hải', ' sóc trăng', ' hà nam',
       ' hậu giang', ' bắc cạn', ' vĩnh phúc', ' bạc liêu',
       ' tỉnh tây ninh', ' campuchia', ' bắc ninh', ' hồ chí minh city',
       ' liên bang nga', '  nha trang',
       ' nghĩa sơn - nghĩa hưng - nam định', ' kontum', ' bình định',
       ' quảng ninh', ' phú thọ', ' lạng sơn', ' bình dương',
       ' cộng hoà séc', ' yên bái', ' ', ' tỉnh đăklăk', ' thái bình',
       ' đăklăk', ' quảng nam', ' nghệ an', ' đồng tháp', ' đăk nông',
       ' quãng ngãi', ' đà lạt', ' lâm đồng', ' hà tĩnh', ' phú yên',
       ' tỉnh ninh thuận', ' đồng nai', ' bình phước ',
       ' tỉnh thanh hóa', ' cao bằng', ' thành phố hồ chí minh',
       ' hà tĩnh ', ' nghệ an ', ' nam định', ' bình thuận ',
       ' bà rịa vũng tàu', ' đồng tháp ', ' hồ chí minh',
       ' tiền giang ', ' bình thuận', ' sóc trăng', ' tỉnh nghệ an',
       ' bình định ', ' tiền giang', ' ninh thuận ', ' quảng ngãi',
       ' bà rịa-vũng tàu', ' quảng trị', '  vũng tàu', ' bến tre',
       ' tỉnh khánh hòa', ' hà nam ', ' australia', ' vĩnh long',
       ' sóc trăng ', ' hòa bình', ' phú yên ', ' quảng nam ',
       ' bạc liêu', ' vũng tàu', ' lai châu', '  buôn ma thuột',
       ' quảng trị ', ' khánh hòa', ' tuyên quang', ' thái nguyên',
       ' quận thủ đức', ' long hồ'], dtype=object)

In [56]:
# Loại bỏ khoảng trắng ở 2 đầu giá trị
df1["noisinh"] = df1["noisinh"].str.strip()
df1["noisinh"].unique()

array(['hồ chí minh', 'đồng tháp', 'hà nam ninh', 'hà tĩnh', 'thanh hóa',
       'quảng ngãi', 'khánh hoà', 'cần thơ', 'gia lai', 'tiền giang',
       'vĩnh long', 'sông bé', 'kiên giang', 'lâm đồng', 'hải dương',
       'trà vinh', 'nam định', 'quảng nam', 'bình thuận', 'quảng bình',
       'bến tre', 'ninh thuận', 'bình định', 'an giang',
       'bà rịa - vũng tàu', 'thừa thiên huế', 'kon tum', 'tây ninh',
       'hà nội', 'đồng nai', 'thanh hoá', 'nghệ an', 'null', 'phú yên',
       'đăk lăk', 'đắc nông', 'bình dương', 'khánh hòa', 'long an',
       'thái bình', 'bình phước', 'hà sơn bình', 'đà nẵng', 'ninh bình',
       'cà mau', 'quảng trị', 'hải hưng', 'hưng yên', 'hà tây', 'đắk lắk',
       'tỉnh đồng nai', 'đắk nông', 'bắc giang', 'hải phòng',
       'tỉnh bình dương', 'minh hải', 'sóc trăng', 'hà nam', 'hậu giang',
       'bắc cạn', 'vĩnh phúc', 'bạc liêu', 'tỉnh tây ninh', 'campuchia',
       'bắc ninh', 'hồ chí minh city', 'liên bang nga', 'nha trang',
       'nghĩa sơn - nghĩa hưng - nam định', 'kontum', 'bình định',
       'quảng ninh', 'phú thọ', 'lạng sơn', 'bình dương', 'cộng hoà séc',
       'yên bái', '', 'tỉnh đăklăk', 'thái bình', 'đăklăk',
       'quảng nam', 'nghệ an', 'đồng tháp', 'đăk nông', 'quãng ngãi',
       'đà lạt', 'lâm đồng', 'hà tĩnh', 'phú yên', 'tỉnh ninh thuận',
       'đồng nai', 'tỉnh thanh hóa', 'cao bằng',
       'thành phố hồ chí minh', 'nam định', 'bà rịa vũng tàu',
       'hồ chí minh', 'bình thuận', 'sóc trăng', 'tỉnh nghệ an',
       'tiền giang', 'quảng ngãi', 'bà rịa-vũng tàu', 'quảng trị',
       'vũng tàu', 'bến tre', 'tỉnh khánh hòa', 'australia',
       'vĩnh long', 'hòa bình', 'bạc liêu', 'lai châu', 'buôn ma thuột',
       'khánh hòa', 'tuyên quang', 'thái nguyên', 'quận thủ đức',
       'long hồ'], dtype=object)

In [57]:
df1['noisinh'].describe()

count            8294
unique            119
top       hồ chí minh
freq             1628
Name: noisinh, dtype: object

### lopsh

In [58]:
# Loaị bỏ khoảng trắng ở 2 đầu giá trị
df1["lopsh"] = df1["lopsh"].str.strip()
df1["lopsh"].unique()

array(['KTPM0001', 'HTTT0001', 'KHMT2013', 'MMTT0001', 'KHMT0001',
       'KHTN2013', 'MTCL2013', 'CNTT2013', 'KTPM2013', 'ANTT2013',
       'KTMT2013', 'PMCL2013', 'MMTT2013', 'KTMT0001', 'CNTT0001',
       'CTTT2013', 'HTTT2013', 'ANTN2013', 'TMĐT2013', 'CNTT2014',
       'KHTN2014', 'HTTT2014', 'ANTT2014', 'KTPM2014', 'KTMT2014',
       'KHMT2014', 'HTCL2014', 'MMTT2014', 'ANTN2014', 'MTCL2014',
       'PMCL2014.1', 'CTTT2014', 'KHMT2016.1', 'PMCL2014', 'TMĐT2014',
       'PMCL2014.2', 'MTLK2015', 'HTTT2015', 'CTTT2015', 'KHMT2015',
       'KTPM2015', 'PMCL2015.1', 'TMĐT2015', 'KHTN2015', 'HTCL2015',
       'ATTT2015', 'MTCL2015.1', 'CNTT2015', 'MMTT2015', 'ATTN2015',
       'KTMT2015', 'PMCL2015.2', 'MTCL2015.2', 'PMCL2015.3', 'HTTT2016',
       'PMCL2016.1', 'CNTT2016', 'HTCL2016.1', 'TMĐT2016', 'MTCL2016.1',
       'ATTN2016', 'KTMT2016', 'ATTT2016', 'KHMT2016', 'MMTT2016',
       'CTTT2016', 'KHTN2016', 'PMCL2016.2', 'MTCL2016.2', 'HTCL2016.2',
       'KHMT2016.2', 'PMCL2016.3', 'KTPM2016', 'KTPM2017', 'ATTN2017',
       'ATTT2017', 'KHMT2017', 'PMCL2017.1', 'HTTT2017', 'KTMT2017',
       'MMTT2017', 'CNTT2017', 'TMĐT2017', 'KHTN2017', 'HTCL2017.1',
       'HTCL2017.2', 'KHCL2017.1', 'PMCL2017.2', 'ATCL2017', 'PMCL2017.3',
       'MTCL2017.1', 'MTCL2017.2', 'MMCL2017', 'CTTT2017', 'KHCL2017.2',
       'PMCL2018.2', 'MTLK2018', 'TMĐT2018', 'KTPM2018', 'PMCL2018.1',
       'KHMT2018', 'CNTT2018', 'HTTT2018', 'ATTN2018', 'ATTT2018',
       'MMTT2018', 'ATCL2018.1', 'KHTN2018', 'HTCL2018.1', 'MTCL2018.1',
       'KTMT2018', 'KHDL2018', 'CNCL2018.1', 'KHCL2018.1', 'KHCL2018.2',
       'CTTT2018', 'MMCL2018.1', 'MTCL2018.2', 'ATCL2018.2', 'CNCL2018.2',
       'HTCL2018.2', 'MMCL2018.2', 'MTCL2018.3', 'KHCL2018.3',
       'KHCL2019.1', 'CTTT2019.1', 'ATCL2019.1', 'TMĐT2019', 'CNTT2019',
       'ATTT2019', 'CNCL2019.1', 'PMCL2019.1', 'KTMT2019', 'KHMT2019',
       'KTPM2019', 'KHDL2019', 'HTTT2019', 'KHTN2019', 'HTCL2019.1',
       'ATTN2019', 'PMCL2019.2', 'MMTT2019', 'MMCL2019.1', 'MTCL2019.1',
       'TMCL2019.1', 'KHCL2019.2', 'CNCL2019.2', 'ATCL2019.2',
       'MTCL2019.2', 'TMCL2019.2', 'HTCL2019.2', 'MMCL2019.2',
       'KHCl2019.3', 'CTTT2019.2', 'KHCL2019.3', 'PMCL2019.3',
       'MTCL2019.3', 'CNCL2019.3', 'TMCL2020'], dtype=object)

In [59]:
df1['lopsh'].describe()

count         8294
unique         159
top       KTPM0001
freq           541
Name: lopsh, dtype: object

### khoa

In [60]:
# Loaị bỏ khoảng trắng ở 2 đầu giá trị
df1["khoa"] = df1["khoa"].str.strip()
df1["khoa"].unique()

array(['CNPM', 'HTTT', 'KHMT', 'MMT&TT', 'KTMT', 'KTTT'], dtype=object)

In [61]:
df1['khoa'].describe()

count       8294
unique         6
top       MMT&TT
freq        1795
Name: khoa, dtype: object

### hedt

In [62]:
# Loaị bỏ khoảng trắng ở 2 đầu giá trị
df1["hedt"] = df1["hedt"].str.strip()
df1["hedt"].unique()

array(['CQUI', 'CTTT', 'CNTN', 'CLC', 'KSTN'], dtype=object)

In [63]:
df1['hedt'].describe()

count     8294
unique       5
top       CQUI
freq      5090
Name: hedt, dtype: object

### khoahoc

In [64]:
# Loaị bỏ khoảng trắng ở 2 đầu giá trị
df1["chuyennganh2"] = df1["chuyennganh2"].str.strip()
df1["chuyennganh2"].unique()

array(['D480103', 'D480104', 'D480101', 'D480201', 'D52480104', 'D480102',
       'D520214', 'D480299', '7480102', '7480201_KHDL', '7480201_CLCN',
       '7480109'], dtype=object)

In [65]:
df1['chuyennganh2'].describe()

count        8294
unique         12
top       D480103
freq         1467
Name: chuyennganh2, dtype: object

### diachi_tinhtp

In [66]:
# Loại bỏ khoảng trắng ở 2 đầu giá trị
df1["diachi_tinhtp"] = df1["diachi_tinhtp"].str.strip()
df1["diachi_tinhtp"].unique()

array(['Thành phố Hồ Chí Minh', 'Huyện Hóc Môn', 'Tỉnh Hà Nam',
       'Tỉnh Hà Tĩnh', 'Tỉnh Thanh Hóa', 'Tình Quảng Ngãi', 'Quận 12',
       'Tỉnh Khánh Hoà', 'Thành phố Cần Thơ', 'Thị xã An Khê',
       'Tỉnh Tiền Giang', 'Huyện Bình Tân', 'Quận Thủ Đức',
       'Phường Phú Cường', 'Tỉnh Lâm Đồng', 'Huyện Di Linh',
       'Tỉnh Kiên Giang', 'Tỉnh Trà Vinh', 'Huyện Đức Hoà',
       'Thành phố Hải Phòng', 'Tỉnh Quảng Nam', 'Huyện Kinh Môn',
       'Tỉnh Bình Thuận', 'Tỉnh Quảng Bình', 'Tỉnh Quảng Ngãi',
       'Thành phố Tây Ninh', 'Thành phố Sa Đéc', 'Tỉnh Ninh Thuận',
       'Tỉnh Gia Lai', 'Tỉnh Vĩnh Phúc', 'Tỉnh An Giang',
       'Thành phố Bà Rịa', 'Tỉnh Thừa Thiên Huế', 'Huyện Kiên Lương',
       'Tỉnh Kon Tum', 'Tỉnh Vĩnh Long', 'Tỉnh Tây Ninh',
       'Thành phố Biên Hoà', 'Huyện Bình Chánh', 'Tình Đồng Nai',
       'Huyện An Biên', 'Huyện Đức Trọng', 'Tỉnh Bình Dương',
       'Tỉnh Nghệ An', 'Tỉnh Bình Định', 'NULL', 'Thành phố Quy Nhơn', '',
       'Huyện Châu Đức', 'Tỉnh Đồng Nai', 'Huyện Bảo Lâm',
       'Huyện Đức Linh', 'Huyện Tháp Mười', 'Tỉnh Phú Yên',
       'Tỉnh Đắk Lắk', 'Huyện Tân Thành', 'Tỉnh Bình Phước',
       'Tỉnh Nam Định', 'Huyện Tánh Linh', 'Tỉnh Đắk Nông',
       'Huyện Thạnh Phú', 'Xã Mỹ Tân', 'Huyện Xuyên Mộc', 'Tỉnh Bến Tre',
       'Huyện Châu Phú', 'Huyện Diên Khánh', 'Huyện Bến Lức',
       'Phường Long Bình', 'Thị xã Gò Công', 'Thành phố Biên Hòa',
       'Tỉnh Đồng Tháp', 'Tỉnh Bà Rịa - Vũng Tàu', 'Tỉnh Long An',
       'Tỉnh Khánh Hòa', 'Huyện Chợ Lách', 'Thị xã Dĩ An',
       'Huyện Chợ Gạo', 'Tân Định', 'Huyện Hàm Thuận Bắc',
       'Huyện Tân Hiệp', 'Huyện Chợ Mới', 'Phường Phước Long B',
       'Huyện Trảng Bom', 'Huyện Đắk Hà', 'Huyện Dương Minh Châu',
       'Thành phố Đà Nẵng', 'Huyện Xuân Lộc', 'Huyện Đức Phổ',
       'Huyện Nhơn Trạch', 'Huyện Quảng Ninh', 'Huyện Lấp Vò',
       'Huyện Dầu Tiếng', 'Thành phố Trà Vinh', 'Tỉnh Cà Mau',
       'Xã Minh Thạnh', 'xã Hựu Thành', 'Tỉnh Quảng Trị',
       'Huyện Phú Giáo', 'Huyện Krông Năng', 'Huyện Long Điền',
       'Xã Tân An Hội', 'Huyện Giồng Trôm', 'Huyện Hoài Nhơn',
       'Thị xã Thuận An', 'Huyện Mộc Hóa', 'Huyện Sơn Tịnh',
       'Huyện Lộc Ninh', 'ấp 4', 'Huyện Cư Kuin', 'Xã Lạc An',
       'Huyện Nghĩa Hành', 'Xã Hố Nai 3', 'Xã Kiểng Phước',
       'Thành phố Thủ Dầu Một', 'Thị xã Long Khánh', 'Huyện Kbang',
       'Thành phố Bảo Lộc', 'Phường Hiệp Ninh', 'Huyện Bình Sơn',
       'Thành phố Vĩnh Long', 'Quận 2', 'Xã Phú Mỹ', 'Huyện Tây Sơn',
       'Huyện Bù Gia Mập', 'Phường Đại Nài', 'Thành phố Phan Thiết',
       'Tỉnh Bạc Liêu', 'Tỉnh Bắc Giang', 'Xã Long An', 'Xã Bàu Đồn',
       'Thị xã An Nhơn', 'Huyện Châu Thành', 'Huyện Hớn Quản',
       'Huyện Hòa Thành', 'Huyện Vĩnh Cửu', 'Xã Ka Đô',
       'Thị xã Đồng Xoài', 'Thành phố Hội An', 'Huyện Cao Lãnh',
       'Huyện Đồng Phú', 'Thành phố Kon Tum', 'Tỉnh Sóc Trăng',
       'Phường Long Trường', 'Tỉnh Thái Bình', 'Huyện Cái Nước',
       'Quận Tân Phú', 'Huyện Phú Hoà', 'Huyện Chơn Thành',
       'Huyện Định Quán', 'Huyện Đăk Mil', 'Huyện Tư Nghĩa',
       'Xã Long Khánh A', 'Phường An Bình', 'Tỉnh Hậu Giang',
       'Tỉnh Thanh Hoá', 'Huyện Cai lậy', 'Huyện Hải Lăng',
       "'Tỉnh Quảng Nam'", "'Tỉnh Tây Ninh'", "'Huyện Cai lậy'",
       "'Huyện Cẩm Mỹ'", "'Tỉnh Tiền Giang'", "'Tỉnh Bình Định'",
       "'Thành phố Cao Lãnh'", "'Huyện Cai Lậy'", "'Tỉnh Phú Yên'",
       "'Huyện Thống Nhất'", "'Phường Phước Bình'", "'Tình Quảng Ngãi'",
       "'Huyện Bắc Tân Uyên'", "'Thị xã Bến Cát'", "'Tỉnh Đắk Lắk'",
       "'Tỉnh Gia Lai'", "'Quận 2'", "'Tỉnh Bến Tre'",
       "'Thành phố Hồ Chí Minh'", "'Tỉnh Nghệ An'",
       "'Tỉnh Bà Rịa - Vũng Tàu'", "'Quận 12'", "'Tỉnh An Giang'",
       "'Tỉnh Bình Dương'", "'Tỉnh Lâm Đồng'", "'Tỉnh Khánh Hoà'",
       "'Phường Hiệp Phú'", "'Thành phố Đà Nẵng'", "'Huyện Hóc Môn'",
       "'Thành phố Mỹ Tho'", "'Huyện Nhơn Trạch'",
       "'Tỉnh Thừa Thiên Huế'", "'Tỉnh Bình Thuận'", "'Tỉnh Long An'",
       "'Tỉnh Đắk Nông'", "'Thành phố Phan Rang -Tháp Chàm'",
       "'Tỉnh Bình Phước'", "'Tình Đồng Nai'", "'Huyện Vạn Ninh'",
       "'Huyện Tân Thạnh'", "'Huyện Ngọc Hồi'", "'Tỉnh Khánh Hòa'",
       "'Huyện Chợ Gạo'", "'Huyện Thanh Bình'", "'Huyện Đạ Tẻh'",
       "'Phường Bình Hưng Hoà A'", "'Huyện Hàm Thuận Bắc'",
       "'Thị xã Hồng Ngự'", "'Tỉnh Quảng Ngãi'", "'Tỉnh Thanh Hóa'",
       "'Huyện Cần Giuộc'", "'Tỉnh Hà Tĩnh'", "'Tỉnh Sóc Trăng'",
       "'Tỉnh Đồng Nai'", "'Thành phố Cần Thơ'", "'Huyện Trảng Bom'",
       "'Huyện Chợ Mới'", "'Tỉnh Quảng Trị'", "'Huyện Bù Gia Mập'",
       "'Huyện Hàm Tân'", "'Huyện Tây Sơn'", "'Huyện Hoài Nhơn'",
       "'Huyện Mỏ Cày Nam'", "'Huyện Kiên Lương'", "'Huyện Sơn Tịnh'",
       "'Huyện Nhà Bè'", "'Xã Nghị Đức'", "'Huyện Lâm Hà'",
       "'Tỉnh Nam Định'", "'Tỉnh Ninh Thuận'", "'Tỉnh Kon Tum'",
       "'Xã Hòa Thuận'", "'Thành phố Tây Ninh'", "'Quận Thủ Đức'",
       "'Huyện Đức Phổ'", "'Huyện Mộ Đức'", "'Huyện Đầm Dơi'",
       "'Quận Tân Bình'", "'Huyện Thanh Hà'", "''", "'Huyện Phù Cát'",
       "'Tỉnh Vĩnh Long'", "'Huyện Cư M\\'gar'", "'Xã An Phước'",
       "'Huyện Châu Đức'", "'Tỉnh Quảng Bình'", "khu phố 1'",
       "'Tỉnh Ninh Bình'", "'Quận 9'", "'Huyện Đức Linh'",
       "'Thành phố Cam Ranh'", "'Huyện Mỹ Đức'", "'Huyện Giồng Trôm'",
       "'Thành phố Pleiku'", "'Huyện Đại Lộc'", "'Huyện Bến Lức'",
       "'Tỉnh Bạc Liêu'", "'Thị xã Bình Minh'", "'Thành phố Quy Nhơn'",
       "'Huyện Tân Hiệp'", "'Thị xã Bình Long'", "'Xã An Hảo'",
       "'Huyện Củ Chi'", "'Tỉnh Kiên Giang'", "'Huyện Sơn Hoà'",
       "'Phường Hưng Bình'", "'Tỉnh Cà Mau'", "'Thành phố Vinh'",
       "'Thị xã Gia Nghĩa'", "'Xã Tân Thông Hội'", "'Huyện Châu Thành'",
       "'Huyện Hòa Thành'", "'xã An Hiệp'", "'Huyện Krông Ana'",
       "'Huyện Long Thành'", "'Huyện Ea Kar'", "'Huyện Đắk R\\'Lấp'",
       "'Xã Vĩnh Hòa Hiệp'", "'Thành phố Biên Hoà'",
       "'Thị xã Kiến Tường'", "KV8'", "'Huyện Đất Đỏ'",
       "'Huyện Tân Thành'", "'Tỉnh Đồng Tháp'", "'Xã Thành Thới A'",
       "'Xã Bưng Riềng'", "'Huyện Đơn Dương'", "'Tỉnh Thanh Hoá'",
       "'Tỉnh Thái Bình'", "'Thị xã Ba Đồn'", "'Thành phố Hải Phòng'",
       "'Huyện Krông Pắc'", "'Quận Bình Tân'", "'Thành phố Rạch Giá'",
       "'Thị xã Hà Tiên'", "'Quận 6'", "'Thị trấn Núi Thành'",
       "'Tỉnh Hải Dương'", "'Thành phố Thủ Dầu Một'", "'Huyện Núi Thành'",
       "'Huyện Lấp Vò'", "'Xã Hòa Định'", "'Phường Tân Hiệp'",
       "'Huyện Hớn Quản'", "'Quận Liên Chiểu'", "'Thành phố Bến Tre'",
       "'Thị xã Đồng Xoài'", "'Quận 7'", "'Huyện Đạ Huoai'",
       "'Xã Long Giang'", "'Quận Bình Thạnh'", "'Thành phố Biên Hòa'",
       "'Huyện Trảng Bàng'", "'Huyện Đông Hoà'", "'Xã Ea Kuăng'",
       "'Thị Trấn Vĩnh Thuận'", "'Xã Tân Ân'", "'Huyện Di Linh'",
       "'Tỉnh Trà Vinh'", "'Thành phố Hà Nội'", "'Xã Long Mỹ'",
       "'Huyện Định Quán'", "'Huyện Đức Trọng'", "'Phường Linh Trung'",
       "'Xã Chi Lăng'", "'Huyện Long Điền'", "'Huyện Tuy Phước'",
       "'Huyện Phong Điền'", "'Huyện Thoại Sơn'", "'Xã Lạc An'",
       "'Thành phố Trà Vinh'", "'Huyện Bình Sơn'", "'Huyện Hải Lăng'",
       "'Huyện Tánh Linh'", "'Phường Tân Thành'", "'Huyện Vĩnh Hưng'",
       "'Xã Tân Mỹ Chánh'", "'Huyện Tân Châu'", "'Huyện Tuy Phong'",
       "'Xã Hội Nghĩa'", "'Huyện Bắc Bình'", "'Thị trấn Ngô Mây'",
       "'Huyện Diên Khánh'", "'Xã Quới An'", "'Huyện Tam Bình'",
       "'Tỉnh Bến Trê'", "'Xã Suối Dây'", "'Xã Sông Ray'",
       "'Huyện Xuyên Mộc'", "'Xã Bảo Bình'", "'Huyện Đức Hoà'",
       "'Huyện Vân Canh'", "'Thành phố Tuy Hoà'", "'Thành phố Cà Mau'",
       "'Tỉnh Hậu Giang'", "'Huyện Krông Búk'", "'Huyện Bù Đốp'",
       "'Huyện Dầu Tiếng'", "'Huyện Phú Quốc'", "'xã Trà Vong'",
       "'Thành phố Châu Đốc'", "'Huyện Long Phú'", "'Huyện Tư Nghĩa'",
       "'Xã Đa Phước Hội'", "'Xã Lương Phú'", "'Huyện Đắk Mil'",
       "'Huyện Quảng Điền'", "'Thành phố Vĩnh Long'", "'Huyện Tháp Mười'",
       "'Thành phố Long Xuyên'", "'Xã An Thái Đông'", "'Xã Nam Chính'",
       "'Huyện Phú Ninh'", "'Phường An Khánh'", "'Quận 5'",
       "'Thành phố Buôn Ma Thuột'", "'Thành phố Tân An'",
       "'Huyện Krông Năng'", "'Huyện Chợ Lách'", "'Huyện Hồng Ngự'",
       "'Thị trấn Tân Bình'", "'Thành phố Hà Tĩnh'", "'Xã Bình Mỹ'",
       "'Huyện Hoài Ân'", "'Huyện Bảo Lâm'", "'Huyện Vĩnh Cửu'",
       "'Xã Thuận Phú'", "'Huyện Tân Uyên'", "'Thành phố Sa Đéc'",
       "'Phường Mỹ Phước'", "'Phường Trảng Dài'", "'Thị xã Thuận An'",
       "'Huyện Bình Đại'", "'Xã Phước Trạch'", "'Thành phố Bảo Lộc'",
       "'Xã Bình Phước Xuân'", "'Thị xã Ngã Năm'", "'Xã Bù Nho'",
       "'Xã Tân Đông'", "Ấp Ba Sa'", "'Huyện Thăng Bình'", "KP 5'",
       "'Thị trấn Vũng Liêm'", "'Thành phố Quảng Ngãi'",
       "'Thành phố Bà Rịa'", "'Xã Phước Thiền'", "'Huyện Bù Đăng'",
       "'Thành phố Tam Kỳ'", "'Phường Long Bình'", "'Xã Mỹ Hội Đông'",
       "'Thị trấn Giồng Trôm'", "'Huyện Bình Chánh'", "'Phường 5'",
       "'Xã Bình Minh'", "'Thành phố Kon Tum'", "'Xã Quảng Tiến'",
       "'Trung Thành'", "'Xã Đông Hòa'", "'Huyện Phú Tân'",
       "'Huyện Thạnh Phú'", "'Thị xã An Nhơn'", "'Huyện Nghĩa Hưng'",
       "'Xã Thuận Hưng'", "'Huyện Chơn Thành'", "'Huyện Nghĩa Hành'",
       "'Quận Gò Vấp'", "'Thành Phố Đà Lạt'", "'Phường Văn Miếu'",
       "'Xã Bình Lộc'", "'Huyện Thủ Thừa'", "'Xuân Bắc'", "ấp 3B'",
       "'Quận 10'", "'Thị xã Long Khánh'", "'Phường Phú Thủy'",
       "'Xã An Châu'", "'Thành phố Sóc Trăng'", "'Quận 11'",
       "'Phường Vĩnh Ngươn'", "'Huyện Mang Thít'", "'Huyện Đức Huệ'",
       "'Xã Phú Xuân'", "'Huyện Cần Đước'", "'Huyện Hoà Bình'",
       "'Huyện Tri Tôn'", "'Huyện Tiên Phước'", "'Thành phố Vị Thanh'",
       "'Xã Tân Thành'", "'Xã Long Thành Trung'", "'Hiệp Phú'",
       "'Xã Lâm San'", "'Huyện Hòa Vang'", "'Huyện Vĩnh Thạnh'",
       "'Xã Hòa Hưng'", "'Thành Phố Đà Nẵng'", "'Xã Hiệp Phước'",
       "'Xã Thiện Tân'", "'Thành phố Huế'", "'Xã Long Điền B'",
       "'Huyện Cư Kuin'", "'Thành phố Bạc Liêu'", "'Xã Suối Nghệ'", "'",
       "'Phường Vĩnh Hải'", "'Thị trấn Tân Phú'", "'Huyện Phú Hoà'",
       "'Xã An Thái Trung'", "'Xã Hòa Lộc'", "'Thị xã Dĩ An'",
       "'Huyện Krông Bông'", "'Đăk Lao'", "'Xã Vĩnh Thạnh'",
       "'Huyện Càng Long'", "'Thị xã Tân Châu'", "'Tân Hiệp'",
       "'Xã Tân Khai'", "'Xã Dưỡng Điềm'", "'Lộc Thái'", "'Huyện Cái Bè'",
       "'Huyện Đức Hòa'", "'Xã Trúc Sơn'", "khu phố Tam Đa'",
       "'Xã Tân Tiến'", "'Huyện Kông Chro'", "Ấp Trung 1'",
       "'Huyện Chư Sê'", "'Xã Liên Hiệp'", "'Phường Long Bình Tân'",
       "'phường Châu Phú B'", "'Huyện Kiến Xương'", "'Xã Thổ Sơn'",
       "'Huyện Dương Minh Châu'", "'Tỉnh Hà Nam'", "'Thành Phố Mỹ Tho'",
       "'Phường Tăng Nhơn Phú A'", "ấp 3'", "'Xã Gia An'",
       "'Xã Đức Phong'", "'Xã Tân Phú'", "'Thị Xã La Gi'",
       "'Quận Thốt Nốt'", "'Huyện Long Hồ'", "'Thị trấn Nam Phước'",
       "'Huyện Cù Lao Dung'", "'Thành phố Thanh Hóa'", "'Huyện Xuân Lộc'",
       "'Xã An Khánh'", "'Thị Xã Đồng Xoài'", "'Thành phố Nha Trang'",
       "'Xã Dray Sáp'", "'Phường Trung Mỹ Tây'", "'Phường 1'",
       "'Phường Linh Chiểu'", "'Phường An Lạc'", "'Huyện Phú Hòa'",
       "'Huyện Trần Đề'", "'Xã Mỹ Thọ'", "'Thành phố Hà nội'",
       "'Xã Tân Hưng'", "'Phường An Bình'", "'Xã Xuân Thạnh'",
       "'Xã Phú Bình'", "'Huyện Lộc Ninh'", "'Xã Tân An'",
       "'Thị xã Cai lậy'", "'Huyện KBang'", "'Quận Tân Phú'",
       "Đường TMT 09'", "'Huyện Phước Sơn'", "'Xã Phú Thuận A'",
       "'xã Đôn Thuận'", "'Thị trấn Liên Nghĩa'", "'Xã Long Hòa'",
       "khu phố 5'", "Ấp 5'", "'Xã Phú Trung'", "'Huyện Châu Phú'",
       "'Xã Bà Điểm'", "'Phường Vĩnh Hòa'", "'Thị xã Sông Cầu'",
       "'Tỉnh Vĩnh Phúc'", "'Quận Hải Châu'", "'phường An Bình'",
       "'Huyện Mỹ Xuyên'", "'Huyện Hòn Đất'", "'Huyện Ba Tri'",
       "'Thị trấn Chi Lăng'", "'Huyện Gò Công Tây'", "'Xã Mỹ Trung'",
       "'Huyện Gio Linh'", "'Quận 4'", "'Huyện Phú Vang'",
       "'Thị xã Vĩnh Châu'", "'Xã Thành Tâm'", "'xã Điện Thọ'",
       "'Tỉnh Bắc Ninh'", "'Xã An Nhơn'", "'Xã Bình Trung'",
       "'xã An Hòa'", "'Xã Tân An Hội'", "'Huyện Phú Riềng'",
       "'Thị trấn Đức Hoà'", "'Huyện An Phú'", "'Xã Tam Quan Nam'",
       "'Thành phố Hội An'", "'Quận Sơn Trà'", "'xã Bình Hiệp'",
       "'Thị xã Hương Thủy'", "'Huyện Phú Lộc'", "'Xã An Hòa'",
       "'Huyện Gò Công Đông'", "'Xã Chí Công'", "'Huyện Quế Sơn'",
       "'Huyện Phước Long'", "'Tỉnh Bắc Giang'", "'Phường Linh Đông'",
       "ấp Hậu Hoa'", "'Tỉnh Hưng Yên'", "'Xã Hóa An'",
       "'Phường Bình An'", "'Huyện Đồng Phú'", "'Xã An Bình'",
       "'Phường Phú Tân'", "'Thị xã Duyên Hải'", "'Xã Đôn Thuận'",
       "'Thành phố Ninh Bình'", "'Quận Thanh Khê'", "'Xã Đức Bình'",
       "'Huyện Hàm Thuận Nam'", "'Xã Long Nguyên'", "'Xã Tân Hiệp B'",
       "thôn III'", "'Huyện Bố Trạch'", "Phường Nghĩa Trung'",
       "'Xã Ea Na'", "'Huyện Cam Lộ'", "'Xã Tân Hội'",
       "'Phường Quang Trung'", "Tỉnh Đắk Lắk'", "'Huyện Hướng Hóa'",
       "'Xã Xuân Bắc'", "'Phường Trường Thọ'", "'Xã Hắc Dịch'",
       "'Xã Bàu Hàm'", "'Phường Linh Xuân'", "tỉnh Đồng Nai'",
       "'Huyện Duy Xuyên'", "'Thành phố Đồng Hới'", "'Phường Châu Phú A'",
       'Bù Gia Mập', "'Huyện Trà Cú'", "'Phường Mỹ Hòa'", "'Xã Ea Tar'",
       "'Thị xã Giá Rai'", "'Huyện Đăk Song'", "'Tỉnh Phú Thọ'",
       "'Xã Long Tân'", "'Huyện Krông Nô'", "'Phường 4'",
       "'Huyện Tân Phú Đông'", "'Huyện Đắk Tô'", "'Phường 3'",
       "'Thành phố Đông Hà'", "'Huyện Bến Cầu'", "'Xã Phú Tân'",
       "'Xã Tân Lập'", "'Phường Truờng Thọ'", "'Xã Nam Thái Sơn'",
       "'Xã Liên Nghĩa'", "'Huyện Cầu Ngang'", "'Huyện Chư Prông'",
       "'Xã Mỹ Hòa Hưng'", "'Phường Phước Hòa'", "'Xã Sông Trầu'",
       "'Huyện U Minh'", "'Huyện Quảng Trạch'", "'Thị trấn Cái Bè'",
       "'Huyện Đông Hòa'", "'Phường Tam Bình'", "'Huyện Lai Vung'",
       "'Huyện Krông Pa'", "'Xã Thạnh Phú'", "'Phường Thị Nại'",
       "'Xã Thạnh Phú Đông'", "'Phường Đông Hưng Thuận'",
       "'Huyện An Minh'", "'Xã Tân Thuận Đông'", "'Xã Nghi Kim'",
       "'Tỉnh Hà Giang'", "'Thành phố Vũng Tàu'", "'Huyện Triệu Phong'",
       "'Huyện Vũng Liêm'", "'Xã Hàm Minh'", "'Quận Ninh Kiều'",
       "'Huyện Cần Giờ'", "'Phường Ninh Sơn'", "'Xã Ngũ Hiệp'",
       "'Huyện Tân Trụ'", "'Phường Tam Phú'", "'Xã Châu Phong'",
       "'Phường Linh Tây'", "'Quận 3'", "'Phường Cẩm Châu'",
       "'Huyện Mỏ Cày Bắc'", "'Huyện Buôn Đôn'",
       "'Phường Tân Chánh Hiệp'", "'Phường Bình Đa'",
       "'Xã Đăng Hưng Phước'", "'Huyện Cư Jút'", "'Xã Chư Gu'",
       "'Phường Hoa Lư'", "'Thị trấn Núi Sập'", "'Huyện Ea Súp'",
       "'Thị xã An Khê'", "Tiền Giang.'", "'Quận Ô Môn'",
       "'Huyện M\\'Đrắk'", "đường 184'", "'Thị trấn Định Quán'",
       "'Xã Kiến An'", "'Xã Cẩm Đường'", "'Phường Tân Phong'",
       "'Thị trấn Long Thành'", "'Huyện Mỹ Tú'", "'Phường Tam Hiệp'",
       "'Xã Tà Đảnh'", "TP HCM'", "'Xã Tân Thanh Tây'",
       "'Phường Thanh Hà'", "'Phường Minh An'", "'Huyện Đam Rông'",
       "'Phường Lê Mao'", "Phú Yên.'", "'Phường 6'", "'Xã Lương Hoà'",
       "'Xã An Vĩnh Ngãi'", "'Phường Nam Lý'", "khu phố 3'",
       "'Thị trấn Tràm Chim'", "'Xã Phú Thanh'", "'Thị xã Ninh Hoà'",
       "'Huyện Trà Ôn'", "'Phường 7'", "'Phường 17'", "'Xã Tam Phước'",
       "'Xã Long An'", "'Thị xã Hoàng Mai'", "'Huyện Gò Dầu'",
       "'Phường Xuân Hòa'", "'Tỉnh Hòa Bình'", "Khu đô thị sinh thái'",
       "'Huyện Lý Sơn'", "Khu phố 6'", "'Thị trấn Krông Năng'",
       "'phường 4'", "'Xã Thiện Trí'", "'Phường Phú Hòa'",
       "'Phường Thuận Hưng'", "'Phường Hiệp Thành'", "'Xã Trung Chánh'",
       "'Huyện Tân Phú'", "'Phường Mỹ Phú'", "'Huyện Cái bè'",
       "'Phường Phước Long A'", "'Xã Phước Tỉnh'", "'Huyện Tiền Hải'",
       "'Xã Cẩm Sơn'", "'Huyện Tân Biên'", "'Huyện Thạch Hà'",
       "'Xã Xuân Tâm'", "'Phường Ngô Quyền'", "'Xã long thọ'",
       "'phường Xuân Trung'", "'Xã Kiểng Phước'", "'Thị xã Gò Công'",
       "'Xã Bình Hải'", "'Xã Hiệp Thạnh'", "'Huyện Thạnh Hóa'",
       "'Xã Vĩnh Hòa'", "'Xã Khánh Thạnh Tân'", "'Xã Hương Mỹ'",
       "'Huyện Đồng Xuân'", "'Tỉnh Điện Biên'", "'Phường Thảo Điền'",
       "'Phường Tân Đông Hiệp'", "'Xã Tam Bình'", "'Xã An Hữu'",
       "'Thị xã Tân Uyên'", "'Huyện Kế Sách'", "'Thành phố Tam Điệp'",
       "'Phường An Phú'", "'Thị trấn Sa Thầy'", "'Xã Trừ Văn Thố'",
       "'Thành phố Tuy Hòa'", "'Xã Bình Giã'", "'Xã Xuân Đông'",
       "'Xã Đông Hà'", "'Huyện Tân Hồng'", "'Xã Kiến Thành'",
       "'Xã Tân Hà'", "'Xã Vũ Hòa'", "'Phường Phú Lợi'",
       "'Thị xã Phước Long'", "'Xã Ka Đô'", "tổ 26'", "'Xã Tân Hiệp'",
       "tỉnh Bình Định'", "'Huyện Tuần Giáo'", "'Xã An Thạnh Thủy'",
       "thành phố Hồ Chí Minh'", "'Thị trấn Thủ Thừa'", "'Xã Phú Lộc'",
       "'Huyện Châu thành'", "'Xã Thạnh Tân'", "'Phường Châu Phú B'",
       "'Quận 8'", "'Xã Hòa Sơn'", "'Thị Xã Buôn Hồ'", "'Xã Thiện Mỹ'",
       "'Huyện Tam Nông'", "'Phường Tự An'", "'Thị trấn Phước An'",
       "'Thị trấn Long Hồ'", "'Xã Cuor Đăng'", "'Phường Phương Đông'",
       "'Huyện Quỳnh Lưu'", "'Tỉnh Quảng Ninh'", "'Xã Bắc Sơn'",
       "'Phường Tân Thới Hiệp'", "'Phường Phú Mỹ'", "'Kiên Giang'",
       "'Gia Lai'", "'Vĩnh Long'", "'An Giang'",
       "'Thị Trấn Dương Minh Châu'", "'Bến Tre'", "'Long An'",
       "'Thị xã Ninh Hòa'", "'Xã Hiếu Phụng'", "'Xã Đồng Phú'",
       "'Thị xã Điện Bàn'", "'Huyện Bình Tân'", "'Phường Bình Chuẩn'",
       "'Huyện Bình Lục'", "'Phường 2'", "'Huyện Tân Phước'",
       "'Xã Long Phước'", "'Phường Bình Chiểu'", "'Đắk Nông'",
       "'Bình Dương'", "'Kon Tum'", "'Tiền Giang'", "'Huyện Hòai Nhơn'",
       "'Xã Mỹ Hòa'", "'Thị trấn Vĩnh An'", "'Xã Vĩnh Thạnh Trung'",
       "'Bình Định'", "'Phường 12'", "'Tỉnh Lạng Sơn'",
       "'Phường Tân Xuân'", "'Phú Yên'", "'Thành phố Phan Thiết'",
       "'Huyện U Minh Thượng'", "'Quảng Ngãi'", "'Huyện Cao Lãnh'",
       "'Xã Tân Bình Thạnh'", "'Huyện Ia Grai'", "'Thị Xã Duyên Hải'",
       "'Đắk Lắk'", "'Huyện Ea H\\'leo'", "khóm Châu Long 2'",
       "'Tây Ninh'", "'Huyện Cầu Kè'", "'Phường Cẩm Thủy'", "ấp 2'",
       "'Khánh Hòa'", "'Thị xã Đồng Xòai'", "'Đồng Nai'", "'Bình Phước'",
       "'Thị trấn Hòa Thành'", "tỉnh Bình Phước'", "'Phường Tân An'",
       "'Xã Bình Trưng'", "'Huyện Quảng Ninh'", 'huyện Đầm Dơi',
       "'Xã Tân Lợi Thạnh'", 'tp Đồng Xoài', "'Huyện Chư Pưh'",
       "'Xã Hố Nai 3'", "'Phường 22'", "'Ninh Thuận'", "'Đồng Tháp'",
       "'Thị trấn Đức Phong'", "'Thái Bình'", "'Huyện Hiệp Hòa'",
       "'Xã Phú Lập'", "'Phường Tân Hòa'", "'Thừa Thiên Huế'",
       "'Phường Định Hòa'", "'Xã Phú Lâm'", "khu phố 6'",
       "'Xã Nghĩa Thành'", "'Phường Đống Đa'", "'Quảng Nam'",
       "'Huyện Hòai Ân'", "'Ninh Bình'", "'Xã Lang Minh'", "Cà Mau'",
       "'Huyện Krông Buk'", "'phường Tân Thới Hiệp'", "'Xã Tam Hiệp'",
       "'Nghệ An'", "'Xã Phú Thạnh'", "'Thành phố Phúc Yên'",
       "'Xã Chà Là'", "'Xã Liên Đầm'", "'Thị trấn Lạc Tánh'",
       "'Phường Uyên Hưng'", "'Huyện Ninh Hải'", "'Xã Long Điền A'",
       "'Phường Phước Nguyên'", "'Thị trấn An Phú'", "'Xã Tân Bình'",
       "'Lâm Đồng'", "'Quảng Bình'", "'Huyện Lệ Thuỷ'",
       "'Huyện Nam Trực'", "'Phường Chánh Nghĩa'", "'Bà Rịa - Vũng Tàu'",
       'quận Thủ Đức', "'Xã Bảo Quang'", "'Huyện Bầu Bàng'",
       "'Phường Khánh Xuân'", 'huyện Tuy Phước', "'Hà Tĩnh'",
       "'Quảng Trị'", "'Xã An Cư'", "khóm Mỹ Thành'", "'Xã Long Khánh A'",
       "'Huyện Tiểu Cần'", "'Xã Bình An'", "Hà Nội'", "'Xã Lâm Sơn'",
       "'Thị trấn Tam Bình'"], dtype=object)

In [67]:
# Loại bỏ kí tự ' ở 2 đầu giá trị (thay thế ' bằng kí tự rỗng)
df1['diachi_tinhtp'] = df1['diachi_tinhtp'].str.replace("'", '', regex=True)
df1["diachi_tinhtp"].unique()

array(['Thành phố Hồ Chí Minh', 'Huyện Hóc Môn', 'Tỉnh Hà Nam',
       'Tỉnh Hà Tĩnh', 'Tỉnh Thanh Hóa', 'Tình Quảng Ngãi', 'Quận 12',
       'Tỉnh Khánh Hoà', 'Thành phố Cần Thơ', 'Thị xã An Khê',
       'Tỉnh Tiền Giang', 'Huyện Bình Tân', 'Quận Thủ Đức',
       'Phường Phú Cường', 'Tỉnh Lâm Đồng', 'Huyện Di Linh',
       'Tỉnh Kiên Giang', 'Tỉnh Trà Vinh', 'Huyện Đức Hoà',
       'Thành phố Hải Phòng', 'Tỉnh Quảng Nam', 'Huyện Kinh Môn',
       'Tỉnh Bình Thuận', 'Tỉnh Quảng Bình', 'Tỉnh Quảng Ngãi',
       'Thành phố Tây Ninh', 'Thành phố Sa Đéc', 'Tỉnh Ninh Thuận',
       'Tỉnh Gia Lai', 'Tỉnh Vĩnh Phúc', 'Tỉnh An Giang',
       'Thành phố Bà Rịa', 'Tỉnh Thừa Thiên Huế', 'Huyện Kiên Lương',
       'Tỉnh Kon Tum', 'Tỉnh Vĩnh Long', 'Tỉnh Tây Ninh',
       'Thành phố Biên Hoà', 'Huyện Bình Chánh', 'Tình Đồng Nai',
       'Huyện An Biên', 'Huyện Đức Trọng', 'Tỉnh Bình Dương',
       'Tỉnh Nghệ An', 'Tỉnh Bình Định', 'NULL', 'Thành phố Quy Nhơn', '',
       'Huyện Châu Đức', 'Tỉnh Đồng Nai', 'Huyện Bảo Lâm',
       'Huyện Đức Linh', 'Huyện Tháp Mười', 'Tỉnh Phú Yên',
       'Tỉnh Đắk Lắk', 'Huyện Tân Thành', 'Tỉnh Bình Phước',
       'Tỉnh Nam Định', 'Huyện Tánh Linh', 'Tỉnh Đắk Nông',
       'Huyện Thạnh Phú', 'Xã Mỹ Tân', 'Huyện Xuyên Mộc', 'Tỉnh Bến Tre',
       'Huyện Châu Phú', 'Huyện Diên Khánh', 'Huyện Bến Lức',
       'Phường Long Bình', 'Thị xã Gò Công', 'Thành phố Biên Hòa',
       'Tỉnh Đồng Tháp', 'Tỉnh Bà Rịa - Vũng Tàu', 'Tỉnh Long An',
       'Tỉnh Khánh Hòa', 'Huyện Chợ Lách', 'Thị xã Dĩ An',
       'Huyện Chợ Gạo', 'Tân Định', 'Huyện Hàm Thuận Bắc',
       'Huyện Tân Hiệp', 'Huyện Chợ Mới', 'Phường Phước Long B',
       'Huyện Trảng Bom', 'Huyện Đắk Hà', 'Huyện Dương Minh Châu',
       'Thành phố Đà Nẵng', 'Huyện Xuân Lộc', 'Huyện Đức Phổ',
       'Huyện Nhơn Trạch', 'Huyện Quảng Ninh', 'Huyện Lấp Vò',
       'Huyện Dầu Tiếng', 'Thành phố Trà Vinh', 'Tỉnh Cà Mau',
       'Xã Minh Thạnh', 'xã Hựu Thành', 'Tỉnh Quảng Trị',
       'Huyện Phú Giáo', 'Huyện Krông Năng', 'Huyện Long Điền',
       'Xã Tân An Hội', 'Huyện Giồng Trôm', 'Huyện Hoài Nhơn',
       'Thị xã Thuận An', 'Huyện Mộc Hóa', 'Huyện Sơn Tịnh',
       'Huyện Lộc Ninh', 'ấp 4', 'Huyện Cư Kuin', 'Xã Lạc An',
       'Huyện Nghĩa Hành', 'Xã Hố Nai 3', 'Xã Kiểng Phước',
       'Thành phố Thủ Dầu Một', 'Thị xã Long Khánh', 'Huyện Kbang',
       'Thành phố Bảo Lộc', 'Phường Hiệp Ninh', 'Huyện Bình Sơn',
       'Thành phố Vĩnh Long', 'Quận 2', 'Xã Phú Mỹ', 'Huyện Tây Sơn',
       'Huyện Bù Gia Mập', 'Phường Đại Nài', 'Thành phố Phan Thiết',
       'Tỉnh Bạc Liêu', 'Tỉnh Bắc Giang', 'Xã Long An', 'Xã Bàu Đồn',
       'Thị xã An Nhơn', 'Huyện Châu Thành', 'Huyện Hớn Quản',
       'Huyện Hòa Thành', 'Huyện Vĩnh Cửu', 'Xã Ka Đô',
       'Thị xã Đồng Xoài', 'Thành phố Hội An', 'Huyện Cao Lãnh',
       'Huyện Đồng Phú', 'Thành phố Kon Tum', 'Tỉnh Sóc Trăng',
       'Phường Long Trường', 'Tỉnh Thái Bình', 'Huyện Cái Nước',
       'Quận Tân Phú', 'Huyện Phú Hoà', 'Huyện Chơn Thành',
       'Huyện Định Quán', 'Huyện Đăk Mil', 'Huyện Tư Nghĩa',
       'Xã Long Khánh A', 'Phường An Bình', 'Tỉnh Hậu Giang',
       'Tỉnh Thanh Hoá', 'Huyện Cai lậy', 'Huyện Hải Lăng',
       'Huyện Cẩm Mỹ', 'Thành phố Cao Lãnh', 'Huyện Cai Lậy',
       'Huyện Thống Nhất', 'Phường Phước Bình', 'Huyện Bắc Tân Uyên',
       'Thị xã Bến Cát', 'Phường Hiệp Phú', 'Thành phố Mỹ Tho',
       'Thành phố Phan Rang -Tháp Chàm', 'Huyện Vạn Ninh',
       'Huyện Tân Thạnh', 'Huyện Ngọc Hồi', 'Huyện Thanh Bình',
       'Huyện Đạ Tẻh', 'Phường Bình Hưng Hoà A', 'Thị xã Hồng Ngự',
       'Huyện Cần Giuộc', 'Huyện Hàm Tân', 'Huyện Mỏ Cày Nam',
       'Huyện Nhà Bè', 'Xã Nghị Đức', 'Huyện Lâm Hà', 'Xã Hòa Thuận',
       'Huyện Mộ Đức', 'Huyện Đầm Dơi', 'Quận Tân Bình', 'Huyện Thanh Hà',
       'Huyện Phù Cát', 'Huyện Cư M\\gar', 'Xã An Phước', 'khu phố 1',
       'Tỉnh Ninh Bình', 'Quận 9', 'Thành phố Cam Ranh', 'Huyện Mỹ Đức',
       'Thành phố Pleiku', 'Huyện Đại Lộc', 'Thị xã Bình Minh',
       'Thị xã Bình Long', 'Xã An Hảo', 'Huyện Củ Chi', 'Huyện Sơn Hoà',
       'Phường Hưng Bình', 'Thành phố Vinh', 'Thị xã Gia Nghĩa',
       'Xã Tân Thông Hội', 'xã An Hiệp', 'Huyện Krông Ana',
       'Huyện Long Thành', 'Huyện Ea Kar', 'Huyện Đắk R\\Lấp',
       'Xã Vĩnh Hòa Hiệp', 'Thị xã Kiến Tường', 'KV8', 'Huyện Đất Đỏ',
       'Xã Thành Thới A', 'Xã Bưng Riềng', 'Huyện Đơn Dương',
       'Thị xã Ba Đồn', 'Huyện Krông Pắc', 'Quận Bình Tân',
       'Thành phố Rạch Giá', 'Thị xã Hà Tiên', 'Quận 6',
       'Thị trấn Núi Thành', 'Tỉnh Hải Dương', 'Huyện Núi Thành',
       'Xã Hòa Định', 'Phường Tân Hiệp', 'Quận Liên Chiểu',
       'Thành phố Bến Tre', 'Quận 7', 'Huyện Đạ Huoai', 'Xã Long Giang',
       'Quận Bình Thạnh', 'Huyện Trảng Bàng', 'Huyện Đông Hoà',
       'Xã Ea Kuăng', 'Thị Trấn Vĩnh Thuận', 'Xã Tân Ân',
       'Thành phố Hà Nội', 'Xã Long Mỹ', 'Phường Linh Trung',
       'Xã Chi Lăng', 'Huyện Tuy Phước', 'Huyện Phong Điền',
       'Huyện Thoại Sơn', 'Phường Tân Thành', 'Huyện Vĩnh Hưng',
       'Xã Tân Mỹ Chánh', 'Huyện Tân Châu', 'Huyện Tuy Phong',
       'Xã Hội Nghĩa', 'Huyện Bắc Bình', 'Thị trấn Ngô Mây',
       'Xã Quới An', 'Huyện Tam Bình', 'Tỉnh Bến Trê', 'Xã Suối Dây',
       'Xã Sông Ray', 'Xã Bảo Bình', 'Huyện Vân Canh',
       'Thành phố Tuy Hoà', 'Thành phố Cà Mau', 'Huyện Krông Búk',
       'Huyện Bù Đốp', 'Huyện Phú Quốc', 'xã Trà Vong',
       'Thành phố Châu Đốc', 'Huyện Long Phú', 'Xã Đa Phước Hội',
       'Xã Lương Phú', 'Huyện Đắk Mil', 'Huyện Quảng Điền',
       'Thành phố Long Xuyên', 'Xã An Thái Đông', 'Xã Nam Chính',
       'Huyện Phú Ninh', 'Phường An Khánh', 'Quận 5',
       'Thành phố Buôn Ma Thuột', 'Thành phố Tân An', 'Huyện Hồng Ngự',
       'Thị trấn Tân Bình', 'Thành phố Hà Tĩnh', 'Xã Bình Mỹ',
       'Huyện Hoài Ân', 'Xã Thuận Phú', 'Huyện Tân Uyên',
       'Phường Mỹ Phước', 'Phường Trảng Dài', 'Huyện Bình Đại',
       'Xã Phước Trạch', 'Xã Bình Phước Xuân', 'Thị xã Ngã Năm',
       'Xã Bù Nho', 'Xã Tân Đông', 'Ấp Ba Sa', 'Huyện Thăng Bình', 'KP 5',
       'Thị trấn Vũng Liêm', 'Thành phố Quảng Ngãi', 'Xã Phước Thiền',
       'Huyện Bù Đăng', 'Thành phố Tam Kỳ', 'Xã Mỹ Hội Đông',
       'Thị trấn Giồng Trôm', 'Phường 5', 'Xã Bình Minh', 'Xã Quảng Tiến',
       'Trung Thành', 'Xã Đông Hòa', 'Huyện Phú Tân', 'Huyện Nghĩa Hưng',
       'Xã Thuận Hưng', 'Quận Gò Vấp', 'Thành Phố Đà Lạt',
       'Phường Văn Miếu', 'Xã Bình Lộc', 'Huyện Thủ Thừa', 'Xuân Bắc',
       'ấp 3B', 'Quận 10', 'Phường Phú Thủy', 'Xã An Châu',
       'Thành phố Sóc Trăng', 'Quận 11', 'Phường Vĩnh Ngươn',
       'Huyện Mang Thít', 'Huyện Đức Huệ', 'Xã Phú Xuân',
       'Huyện Cần Đước', 'Huyện Hoà Bình', 'Huyện Tri Tôn',
       'Huyện Tiên Phước', 'Thành phố Vị Thanh', 'Xã Tân Thành',
       'Xã Long Thành Trung', 'Hiệp Phú', 'Xã Lâm San', 'Huyện Hòa Vang',
       'Huyện Vĩnh Thạnh', 'Xã Hòa Hưng', 'Thành Phố Đà Nẵng',
       'Xã Hiệp Phước', 'Xã Thiện Tân', 'Thành phố Huế', 'Xã Long Điền B',
       'Thành phố Bạc Liêu', 'Xã Suối Nghệ', 'Phường Vĩnh Hải',
       'Thị trấn Tân Phú', 'Xã An Thái Trung', 'Xã Hòa Lộc',
       'Huyện Krông Bông', 'Đăk Lao', 'Xã Vĩnh Thạnh', 'Huyện Càng Long',
       'Thị xã Tân Châu', 'Tân Hiệp', 'Xã Tân Khai', 'Xã Dưỡng Điềm',
       'Lộc Thái', 'Huyện Cái Bè', 'Huyện Đức Hòa', 'Xã Trúc Sơn',
       'khu phố Tam Đa', 'Xã Tân Tiến', 'Huyện Kông Chro', 'Ấp Trung 1',
       'Huyện Chư Sê', 'Xã Liên Hiệp', 'Phường Long Bình Tân',
       'phường Châu Phú B', 'Huyện Kiến Xương', 'Xã Thổ Sơn',
       'Thành Phố Mỹ Tho', 'Phường Tăng Nhơn Phú A', 'ấp 3', 'Xã Gia An',
       'Xã Đức Phong', 'Xã Tân Phú', 'Thị Xã La Gi', 'Quận Thốt Nốt',
       'Huyện Long Hồ', 'Thị trấn Nam Phước', 'Huyện Cù Lao Dung',
       'Thành phố Thanh Hóa', 'Xã An Khánh', 'Thị Xã Đồng Xoài',
       'Thành phố Nha Trang', 'Xã Dray Sáp', 'Phường Trung Mỹ Tây',
       'Phường 1', 'Phường Linh Chiểu', 'Phường An Lạc', 'Huyện Phú Hòa',
       'Huyện Trần Đề', 'Xã Mỹ Thọ', 'Thành phố Hà nội', 'Xã Tân Hưng',
       'Xã Xuân Thạnh', 'Xã Phú Bình', 'Xã Tân An', 'Thị xã Cai lậy',
       'Huyện KBang', 'Đường TMT 09', 'Huyện Phước Sơn', 'Xã Phú Thuận A',
       'xã Đôn Thuận', 'Thị trấn Liên Nghĩa', 'Xã Long Hòa', 'khu phố 5',
       'Ấp 5', 'Xã Phú Trung', 'Xã Bà Điểm', 'Phường Vĩnh Hòa',
       'Thị xã Sông Cầu', 'Quận Hải Châu', 'phường An Bình',
       'Huyện Mỹ Xuyên', 'Huyện Hòn Đất', 'Huyện Ba Tri',
       'Thị trấn Chi Lăng', 'Huyện Gò Công Tây', 'Xã Mỹ Trung',
       'Huyện Gio Linh', 'Quận 4', 'Huyện Phú Vang', 'Thị xã Vĩnh Châu',
       'Xã Thành Tâm', 'xã Điện Thọ', 'Tỉnh Bắc Ninh', 'Xã An Nhơn',
       'Xã Bình Trung', 'xã An Hòa', 'Huyện Phú Riềng',
       'Thị trấn Đức Hoà', 'Huyện An Phú', 'Xã Tam Quan Nam',
       'Quận Sơn Trà', 'xã Bình Hiệp', 'Thị xã Hương Thủy',
       'Huyện Phú Lộc', 'Xã An Hòa', 'Huyện Gò Công Đông', 'Xã Chí Công',
       'Huyện Quế Sơn', 'Huyện Phước Long', 'Phường Linh Đông',
       'ấp Hậu Hoa', 'Tỉnh Hưng Yên', 'Xã Hóa An', 'Phường Bình An',
       'Xã An Bình', 'Phường Phú Tân', 'Thị xã Duyên Hải', 'Xã Đôn Thuận',
       'Thành phố Ninh Bình', 'Quận Thanh Khê', 'Xã Đức Bình',
       'Huyện Hàm Thuận Nam', 'Xã Long Nguyên', 'Xã Tân Hiệp B',
       'thôn III', 'Huyện Bố Trạch', 'Phường Nghĩa Trung', 'Xã Ea Na',
       'Huyện Cam Lộ', 'Xã Tân Hội', 'Phường Quang Trung',
       'Huyện Hướng Hóa', 'Xã Xuân Bắc', 'Phường Trường Thọ',
       'Xã Hắc Dịch', 'Xã Bàu Hàm', 'Phường Linh Xuân', 'tỉnh Đồng Nai',
       'Huyện Duy Xuyên', 'Thành phố Đồng Hới', 'Phường Châu Phú A',
       'Bù Gia Mập', 'Huyện Trà Cú', 'Phường Mỹ Hòa', 'Xã Ea Tar',
       'Thị xã Giá Rai', 'Huyện Đăk Song', 'Tỉnh Phú Thọ', 'Xã Long Tân',
       'Huyện Krông Nô', 'Phường 4', 'Huyện Tân Phú Đông', 'Huyện Đắk Tô',
       'Phường 3', 'Thành phố Đông Hà', 'Huyện Bến Cầu', 'Xã Phú Tân',
       'Xã Tân Lập', 'Phường Truờng Thọ', 'Xã Nam Thái Sơn',
       'Xã Liên Nghĩa', 'Huyện Cầu Ngang', 'Huyện Chư Prông',
       'Xã Mỹ Hòa Hưng', 'Phường Phước Hòa', 'Xã Sông Trầu',
       'Huyện U Minh', 'Huyện Quảng Trạch', 'Thị trấn Cái Bè',
       'Huyện Đông Hòa', 'Phường Tam Bình', 'Huyện Lai Vung',
       'Huyện Krông Pa', 'Xã Thạnh Phú', 'Phường Thị Nại',
       'Xã Thạnh Phú Đông', 'Phường Đông Hưng Thuận', 'Huyện An Minh',
       'Xã Tân Thuận Đông', 'Xã Nghi Kim', 'Tỉnh Hà Giang',
       'Thành phố Vũng Tàu', 'Huyện Triệu Phong', 'Huyện Vũng Liêm',
       'Xã Hàm Minh', 'Quận Ninh Kiều', 'Huyện Cần Giờ',
       'Phường Ninh Sơn', 'Xã Ngũ Hiệp', 'Huyện Tân Trụ',
       'Phường Tam Phú', 'Xã Châu Phong', 'Phường Linh Tây', 'Quận 3',
       'Phường Cẩm Châu', 'Huyện Mỏ Cày Bắc', 'Huyện Buôn Đôn',
       'Phường Tân Chánh Hiệp', 'Phường Bình Đa', 'Xã Đăng Hưng Phước',
       'Huyện Cư Jút', 'Xã Chư Gu', 'Phường Hoa Lư', 'Thị trấn Núi Sập',
       'Huyện Ea Súp', 'Tiền Giang.', 'Quận Ô Môn', 'Huyện M\\Đrắk',
       'đường 184', 'Thị trấn Định Quán', 'Xã Kiến An', 'Xã Cẩm Đường',
       'Phường Tân Phong', 'Thị trấn Long Thành', 'Huyện Mỹ Tú',
       'Phường Tam Hiệp', 'Xã Tà Đảnh', 'TP HCM', 'Xã Tân Thanh Tây',
       'Phường Thanh Hà', 'Phường Minh An', 'Huyện Đam Rông',
       'Phường Lê Mao', 'Phú Yên.', 'Phường 6', 'Xã Lương Hoà',
       'Xã An Vĩnh Ngãi', 'Phường Nam Lý', 'khu phố 3',
       'Thị trấn Tràm Chim', 'Xã Phú Thanh', 'Thị xã Ninh Hoà',
       'Huyện Trà Ôn', 'Phường 7', 'Phường 17', 'Xã Tam Phước',
       'Thị xã Hoàng Mai', 'Huyện Gò Dầu', 'Phường Xuân Hòa',
       'Tỉnh Hòa Bình', 'Khu đô thị sinh thái', 'Huyện Lý Sơn',
       'Khu phố 6', 'Thị trấn Krông Năng', 'phường 4', 'Xã Thiện Trí',
       'Phường Phú Hòa', 'Phường Thuận Hưng', 'Phường Hiệp Thành',
       'Xã Trung Chánh', 'Huyện Tân Phú', 'Phường Mỹ Phú', 'Huyện Cái bè',
       'Phường Phước Long A', 'Xã Phước Tỉnh', 'Huyện Tiền Hải',
       'Xã Cẩm Sơn', 'Huyện Tân Biên', 'Huyện Thạch Hà', 'Xã Xuân Tâm',
       'Phường Ngô Quyền', 'Xã long thọ', 'phường Xuân Trung',
       'Xã Bình Hải', 'Xã Hiệp Thạnh', 'Huyện Thạnh Hóa', 'Xã Vĩnh Hòa',
       'Xã Khánh Thạnh Tân', 'Xã Hương Mỹ', 'Huyện Đồng Xuân',
       'Tỉnh Điện Biên', 'Phường Thảo Điền', 'Phường Tân Đông Hiệp',
       'Xã Tam Bình', 'Xã An Hữu', 'Thị xã Tân Uyên', 'Huyện Kế Sách',
       'Thành phố Tam Điệp', 'Phường An Phú', 'Thị trấn Sa Thầy',
       'Xã Trừ Văn Thố', 'Thành phố Tuy Hòa', 'Xã Bình Giã',
       'Xã Xuân Đông', 'Xã Đông Hà', 'Huyện Tân Hồng', 'Xã Kiến Thành',
       'Xã Tân Hà', 'Xã Vũ Hòa', 'Phường Phú Lợi', 'Thị xã Phước Long',
       'tổ 26', 'Xã Tân Hiệp', 'tỉnh Bình Định', 'Huyện Tuần Giáo',
       'Xã An Thạnh Thủy', 'thành phố Hồ Chí Minh', 'Thị trấn Thủ Thừa',
       'Xã Phú Lộc', 'Huyện Châu thành', 'Xã Thạnh Tân',
       'Phường Châu Phú B', 'Quận 8', 'Xã Hòa Sơn', 'Thị Xã Buôn Hồ',
       'Xã Thiện Mỹ', 'Huyện Tam Nông', 'Phường Tự An',
       'Thị trấn Phước An', 'Thị trấn Long Hồ', 'Xã Cuor Đăng',
       'Phường Phương Đông', 'Huyện Quỳnh Lưu', 'Tỉnh Quảng Ninh',
       'Xã Bắc Sơn', 'Phường Tân Thới Hiệp', 'Phường Phú Mỹ',
       'Kiên Giang', 'Gia Lai', 'Vĩnh Long', 'An Giang',
       'Thị Trấn Dương Minh Châu', 'Bến Tre', 'Long An',
       'Thị xã Ninh Hòa', 'Xã Hiếu Phụng', 'Xã Đồng Phú',
       'Thị xã Điện Bàn', 'Phường Bình Chuẩn', 'Huyện Bình Lục',
       'Phường 2', 'Huyện Tân Phước', 'Xã Long Phước',
       'Phường Bình Chiểu', 'Đắk Nông', 'Bình Dương', 'Kon Tum',
       'Tiền Giang', 'Huyện Hòai Nhơn', 'Xã Mỹ Hòa', 'Thị trấn Vĩnh An',
       'Xã Vĩnh Thạnh Trung', 'Bình Định', 'Phường 12', 'Tỉnh Lạng Sơn',
       'Phường Tân Xuân', 'Phú Yên', 'Huyện U Minh Thượng', 'Quảng Ngãi',
       'Xã Tân Bình Thạnh', 'Huyện Ia Grai', 'Thị Xã Duyên Hải',
       'Đắk Lắk', 'Huyện Ea H\\leo', 'khóm Châu Long 2', 'Tây Ninh',
       'Huyện Cầu Kè', 'Phường Cẩm Thủy', 'ấp 2', 'Khánh Hòa',
       'Thị xã Đồng Xòai', 'Đồng Nai', 'Bình Phước', 'Thị trấn Hòa Thành',
       'tỉnh Bình Phước', 'Phường Tân An', 'Xã Bình Trưng',
       'huyện Đầm Dơi', 'Xã Tân Lợi Thạnh', 'tp Đồng Xoài',
       'Huyện Chư Pưh', 'Phường 22', 'Ninh Thuận', 'Đồng Tháp',
       'Thị trấn Đức Phong', 'Thái Bình', 'Huyện Hiệp Hòa', 'Xã Phú Lập',
       'Phường Tân Hòa', 'Thừa Thiên Huế', 'Phường Định Hòa',
       'Xã Phú Lâm', 'khu phố 6', 'Xã Nghĩa Thành', 'Phường Đống Đa',
       'Quảng Nam', 'Huyện Hòai Ân', 'Ninh Bình', 'Xã Lang Minh',
       'Cà Mau', 'Huyện Krông Buk', 'phường Tân Thới Hiệp', 'Xã Tam Hiệp',
       'Nghệ An', 'Xã Phú Thạnh', 'Thành phố Phúc Yên', 'Xã Chà Là',
       'Xã Liên Đầm', 'Thị trấn Lạc Tánh', 'Phường Uyên Hưng',
       'Huyện Ninh Hải', 'Xã Long Điền A', 'Phường Phước Nguyên',
       'Thị trấn An Phú', 'Xã Tân Bình', 'Lâm Đồng', 'Quảng Bình',
       'Huyện Lệ Thuỷ', 'Huyện Nam Trực', 'Phường Chánh Nghĩa',
       'Bà Rịa - Vũng Tàu', 'quận Thủ Đức', 'Xã Bảo Quang',
       'Huyện Bầu Bàng', 'Phường Khánh Xuân', 'huyện Tuy Phước',
       'Hà Tĩnh', 'Quảng Trị', 'Xã An Cư', 'khóm Mỹ Thành',
       'Huyện Tiểu Cần', 'Xã Bình An', 'Hà Nội', 'Xã Lâm Sơn',
       'Thị trấn Tam Bình'], dtype=object)

In [68]:
# Định dạng in hoa ở mỗi kí tự đầu tiên
df1['diachi_tinhtp'] = df1['diachi_tinhtp'].str.lower()
df1["diachi_tinhtp"].unique()

array(['thành phố hồ chí minh', 'huyện hóc môn', 'tỉnh hà nam',
       'tỉnh hà tĩnh', 'tỉnh thanh hóa', 'tình quảng ngãi', 'quận 12',
       'tỉnh khánh hoà', 'thành phố cần thơ', 'thị xã an khê',
       'tỉnh tiền giang', 'huyện bình tân', 'quận thủ đức',
       'phường phú cường', 'tỉnh lâm đồng', 'huyện di linh',
       'tỉnh kiên giang', 'tỉnh trà vinh', 'huyện đức hoà',
       'thành phố hải phòng', 'tỉnh quảng nam', 'huyện kinh môn',
       'tỉnh bình thuận', 'tỉnh quảng bình', 'tỉnh quảng ngãi',
       'thành phố tây ninh', 'thành phố sa đéc', 'tỉnh ninh thuận',
       'tỉnh gia lai', 'tỉnh vĩnh phúc', 'tỉnh an giang',
       'thành phố bà rịa', 'tỉnh thừa thiên huế', 'huyện kiên lương',
       'tỉnh kon tum', 'tỉnh vĩnh long', 'tỉnh tây ninh',
       'thành phố biên hoà', 'huyện bình chánh', 'tình đồng nai',
       'huyện an biên', 'huyện đức trọng', 'tỉnh bình dương',
       'tỉnh nghệ an', 'tỉnh bình định', 'null', 'thành phố quy nhơn', '',
       'huyện châu đức', 'tỉnh đồng nai', 'huyện bảo lâm',
       'huyện đức linh', 'huyện tháp mười', 'tỉnh phú yên',
       'tỉnh đắk lắk', 'huyện tân thành', 'tỉnh bình phước',
       'tỉnh nam định', 'huyện tánh linh', 'tỉnh đắk nông',
       'huyện thạnh phú', 'xã mỹ tân', 'huyện xuyên mộc', 'tỉnh bến tre',
       'huyện châu phú', 'huyện diên khánh', 'huyện bến lức',
       'phường long bình', 'thị xã gò công', 'thành phố biên hòa',
       'tỉnh đồng tháp', 'tỉnh bà rịa - vũng tàu', 'tỉnh long an',
       'tỉnh khánh hòa', 'huyện chợ lách', 'thị xã dĩ an',
       'huyện chợ gạo', 'tân định', 'huyện hàm thuận bắc',
       'huyện tân hiệp', 'huyện chợ mới', 'phường phước long b',
       'huyện trảng bom', 'huyện đắk hà', 'huyện dương minh châu',
       'thành phố đà nẵng', 'huyện xuân lộc', 'huyện đức phổ',
       'huyện nhơn trạch', 'huyện quảng ninh', 'huyện lấp vò',
       'huyện dầu tiếng', 'thành phố trà vinh', 'tỉnh cà mau',
       'xã minh thạnh', 'xã hựu thành', 'tỉnh quảng trị',
       'huyện phú giáo', 'huyện krông năng', 'huyện long điền',
       'xã tân an hội', 'huyện giồng trôm', 'huyện hoài nhơn',
       'thị xã thuận an', 'huyện mộc hóa', 'huyện sơn tịnh',
       'huyện lộc ninh', 'ấp 4', 'huyện cư kuin', 'xã lạc an',
       'huyện nghĩa hành', 'xã hố nai 3', 'xã kiểng phước',
       'thành phố thủ dầu một', 'thị xã long khánh', 'huyện kbang',
       'thành phố bảo lộc', 'phường hiệp ninh', 'huyện bình sơn',
       'thành phố vĩnh long', 'quận 2', 'xã phú mỹ', 'huyện tây sơn',
       'huyện bù gia mập', 'phường đại nài', 'thành phố phan thiết',
       'tỉnh bạc liêu', 'tỉnh bắc giang', 'xã long an', 'xã bàu đồn',
       'thị xã an nhơn', 'huyện châu thành', 'huyện hớn quản',
       'huyện hòa thành', 'huyện vĩnh cửu', 'xã ka đô',
       'thị xã đồng xoài', 'thành phố hội an', 'huyện cao lãnh',
       'huyện đồng phú', 'thành phố kon tum', 'tỉnh sóc trăng',
       'phường long trường', 'tỉnh thái bình', 'huyện cái nước',
       'quận tân phú', 'huyện phú hoà', 'huyện chơn thành',
       'huyện định quán', 'huyện đăk mil', 'huyện tư nghĩa',
       'xã long khánh a', 'phường an bình', 'tỉnh hậu giang',
       'tỉnh thanh hoá', 'huyện cai lậy', 'huyện hải lăng',
       'huyện cẩm mỹ', 'thành phố cao lãnh', 'huyện thống nhất',
       'phường phước bình', 'huyện bắc tân uyên', 'thị xã bến cát',
       'phường hiệp phú', 'thành phố mỹ tho',
       'thành phố phan rang -tháp chàm', 'huyện vạn ninh',
       'huyện tân thạnh', 'huyện ngọc hồi', 'huyện thanh bình',
       'huyện đạ tẻh', 'phường bình hưng hoà a', 'thị xã hồng ngự',
       'huyện cần giuộc', 'huyện hàm tân', 'huyện mỏ cày nam',
       'huyện nhà bè', 'xã nghị đức', 'huyện lâm hà', 'xã hòa thuận',
       'huyện mộ đức', 'huyện đầm dơi', 'quận tân bình', 'huyện thanh hà',
       'huyện phù cát', 'huyện cư m\\gar', 'xã an phước', 'khu phố 1',
       'tỉnh ninh bình', 'quận 9', 'thành phố cam ranh', 'huyện mỹ đức',
       'thành phố pleiku', 'huyện đại lộc', 'thị xã bình minh',
       'thị xã bình long', 'xã an hảo', 'huyện củ chi', 'huyện sơn hoà',
       'phường hưng bình', 'thành phố vinh', 'thị xã gia nghĩa',
       'xã tân thông hội', 'xã an hiệp', 'huyện krông ana',
       'huyện long thành', 'huyện ea kar', 'huyện đắk r\\lấp',
       'xã vĩnh hòa hiệp', 'thị xã kiến tường', 'kv8', 'huyện đất đỏ',
       'xã thành thới a', 'xã bưng riềng', 'huyện đơn dương',
       'thị xã ba đồn', 'huyện krông pắc', 'quận bình tân',
       'thành phố rạch giá', 'thị xã hà tiên', 'quận 6',
       'thị trấn núi thành', 'tỉnh hải dương', 'huyện núi thành',
       'xã hòa định', 'phường tân hiệp', 'quận liên chiểu',
       'thành phố bến tre', 'quận 7', 'huyện đạ huoai', 'xã long giang',
       'quận bình thạnh', 'huyện trảng bàng', 'huyện đông hoà',
       'xã ea kuăng', 'thị trấn vĩnh thuận', 'xã tân ân',
       'thành phố hà nội', 'xã long mỹ', 'phường linh trung',
       'xã chi lăng', 'huyện tuy phước', 'huyện phong điền',
       'huyện thoại sơn', 'phường tân thành', 'huyện vĩnh hưng',
       'xã tân mỹ chánh', 'huyện tân châu', 'huyện tuy phong',
       'xã hội nghĩa', 'huyện bắc bình', 'thị trấn ngô mây',
       'xã quới an', 'huyện tam bình', 'tỉnh bến trê', 'xã suối dây',
       'xã sông ray', 'xã bảo bình', 'huyện vân canh',
       'thành phố tuy hoà', 'thành phố cà mau', 'huyện krông búk',
       'huyện bù đốp', 'huyện phú quốc', 'xã trà vong',
       'thành phố châu đốc', 'huyện long phú', 'xã đa phước hội',
       'xã lương phú', 'huyện đắk mil', 'huyện quảng điền',
       'thành phố long xuyên', 'xã an thái đông', 'xã nam chính',
       'huyện phú ninh', 'phường an khánh', 'quận 5',
       'thành phố buôn ma thuột', 'thành phố tân an', 'huyện hồng ngự',
       'thị trấn tân bình', 'thành phố hà tĩnh', 'xã bình mỹ',
       'huyện hoài ân', 'xã thuận phú', 'huyện tân uyên',
       'phường mỹ phước', 'phường trảng dài', 'huyện bình đại',
       'xã phước trạch', 'xã bình phước xuân', 'thị xã ngã năm',
       'xã bù nho', 'xã tân đông', 'ấp ba sa', 'huyện thăng bình', 'kp 5',
       'thị trấn vũng liêm', 'thành phố quảng ngãi', 'xã phước thiền',
       'huyện bù đăng', 'thành phố tam kỳ', 'xã mỹ hội đông',
       'thị trấn giồng trôm', 'phường 5', 'xã bình minh', 'xã quảng tiến',
       'trung thành', 'xã đông hòa', 'huyện phú tân', 'huyện nghĩa hưng',
       'xã thuận hưng', 'quận gò vấp', 'thành phố đà lạt',
       'phường văn miếu', 'xã bình lộc', 'huyện thủ thừa', 'xuân bắc',
       'ấp 3b', 'quận 10', 'phường phú thủy', 'xã an châu',
       'thành phố sóc trăng', 'quận 11', 'phường vĩnh ngươn',
       'huyện mang thít', 'huyện đức huệ', 'xã phú xuân',
       'huyện cần đước', 'huyện hoà bình', 'huyện tri tôn',
       'huyện tiên phước', 'thành phố vị thanh', 'xã tân thành',
       'xã long thành trung', 'hiệp phú', 'xã lâm san', 'huyện hòa vang',
       'huyện vĩnh thạnh', 'xã hòa hưng', 'xã hiệp phước', 'xã thiện tân',
       'thành phố huế', 'xã long điền b', 'thành phố bạc liêu',
       'xã suối nghệ', 'phường vĩnh hải', 'thị trấn tân phú',
       'xã an thái trung', 'xã hòa lộc', 'huyện krông bông', 'đăk lao',
       'xã vĩnh thạnh', 'huyện càng long', 'thị xã tân châu', 'tân hiệp',
       'xã tân khai', 'xã dưỡng điềm', 'lộc thái', 'huyện cái bè',
       'huyện đức hòa', 'xã trúc sơn', 'khu phố tam đa', 'xã tân tiến',
       'huyện kông chro', 'ấp trung 1', 'huyện chư sê', 'xã liên hiệp',
       'phường long bình tân', 'phường châu phú b', 'huyện kiến xương',
       'xã thổ sơn', 'phường tăng nhơn phú a', 'ấp 3', 'xã gia an',
       'xã đức phong', 'xã tân phú', 'thị xã la gi', 'quận thốt nốt',
       'huyện long hồ', 'thị trấn nam phước', 'huyện cù lao dung',
       'thành phố thanh hóa', 'xã an khánh', 'thành phố nha trang',
       'xã dray sáp', 'phường trung mỹ tây', 'phường 1',
       'phường linh chiểu', 'phường an lạc', 'huyện phú hòa',
       'huyện trần đề', 'xã mỹ thọ', 'xã tân hưng', 'xã xuân thạnh',
       'xã phú bình', 'xã tân an', 'thị xã cai lậy', 'đường tmt 09',
       'huyện phước sơn', 'xã phú thuận a', 'xã đôn thuận',
       'thị trấn liên nghĩa', 'xã long hòa', 'khu phố 5', 'ấp 5',
       'xã phú trung', 'xã bà điểm', 'phường vĩnh hòa', 'thị xã sông cầu',
       'quận hải châu', 'huyện mỹ xuyên', 'huyện hòn đất', 'huyện ba tri',
       'thị trấn chi lăng', 'huyện gò công tây', 'xã mỹ trung',
       'huyện gio linh', 'quận 4', 'huyện phú vang', 'thị xã vĩnh châu',
       'xã thành tâm', 'xã điện thọ', 'tỉnh bắc ninh', 'xã an nhơn',
       'xã bình trung', 'xã an hòa', 'huyện phú riềng',
       'thị trấn đức hoà', 'huyện an phú', 'xã tam quan nam',
       'quận sơn trà', 'xã bình hiệp', 'thị xã hương thủy',
       'huyện phú lộc', 'huyện gò công đông', 'xã chí công',
       'huyện quế sơn', 'huyện phước long', 'phường linh đông',
       'ấp hậu hoa', 'tỉnh hưng yên', 'xã hóa an', 'phường bình an',
       'xã an bình', 'phường phú tân', 'thị xã duyên hải',
       'thành phố ninh bình', 'quận thanh khê', 'xã đức bình',
       'huyện hàm thuận nam', 'xã long nguyên', 'xã tân hiệp b',
       'thôn iii', 'huyện bố trạch', 'phường nghĩa trung', 'xã ea na',
       'huyện cam lộ', 'xã tân hội', 'phường quang trung',
       'huyện hướng hóa', 'xã xuân bắc', 'phường trường thọ',
       'xã hắc dịch', 'xã bàu hàm', 'phường linh xuân', 'huyện duy xuyên',
       'thành phố đồng hới', 'phường châu phú a', 'bù gia mập',
       'huyện trà cú', 'phường mỹ hòa', 'xã ea tar', 'thị xã giá rai',
       'huyện đăk song', 'tỉnh phú thọ', 'xã long tân', 'huyện krông nô',
       'phường 4', 'huyện tân phú đông', 'huyện đắk tô', 'phường 3',
       'thành phố đông hà', 'huyện bến cầu', 'xã phú tân', 'xã tân lập',
       'phường truờng thọ', 'xã nam thái sơn', 'xã liên nghĩa',
       'huyện cầu ngang', 'huyện chư prông', 'xã mỹ hòa hưng',
       'phường phước hòa', 'xã sông trầu', 'huyện u minh',
       'huyện quảng trạch', 'thị trấn cái bè', 'huyện đông hòa',
       'phường tam bình', 'huyện lai vung', 'huyện krông pa',
       'xã thạnh phú', 'phường thị nại', 'xã thạnh phú đông',
       'phường đông hưng thuận', 'huyện an minh', 'xã tân thuận đông',
       'xã nghi kim', 'tỉnh hà giang', 'thành phố vũng tàu',
       'huyện triệu phong', 'huyện vũng liêm', 'xã hàm minh',
       'quận ninh kiều', 'huyện cần giờ', 'phường ninh sơn',
       'xã ngũ hiệp', 'huyện tân trụ', 'phường tam phú', 'xã châu phong',
       'phường linh tây', 'quận 3', 'phường cẩm châu', 'huyện mỏ cày bắc',
       'huyện buôn đôn', 'phường tân chánh hiệp', 'phường bình đa',
       'xã đăng hưng phước', 'huyện cư jút', 'xã chư gu', 'phường hoa lư',
       'thị trấn núi sập', 'huyện ea súp', 'tiền giang.', 'quận ô môn',
       'huyện m\\đrắk', 'đường 184', 'thị trấn định quán', 'xã kiến an',
       'xã cẩm đường', 'phường tân phong', 'thị trấn long thành',
       'huyện mỹ tú', 'phường tam hiệp', 'xã tà đảnh', 'tp hcm',
       'xã tân thanh tây', 'phường thanh hà', 'phường minh an',
       'huyện đam rông', 'phường lê mao', 'phú yên.', 'phường 6',
       'xã lương hoà', 'xã an vĩnh ngãi', 'phường nam lý', 'khu phố 3',
       'thị trấn tràm chim', 'xã phú thanh', 'thị xã ninh hoà',
       'huyện trà ôn', 'phường 7', 'phường 17', 'xã tam phước',
       'thị xã hoàng mai', 'huyện gò dầu', 'phường xuân hòa',
       'tỉnh hòa bình', 'khu đô thị sinh thái', 'huyện lý sơn',
       'khu phố 6', 'thị trấn krông năng', 'xã thiện trí',
       'phường phú hòa', 'phường thuận hưng', 'phường hiệp thành',
       'xã trung chánh', 'huyện tân phú', 'phường mỹ phú',
       'phường phước long a', 'xã phước tỉnh', 'huyện tiền hải',
       'xã cẩm sơn', 'huyện tân biên', 'huyện thạch hà', 'xã xuân tâm',
       'phường ngô quyền', 'xã long thọ', 'phường xuân trung',
       'xã bình hải', 'xã hiệp thạnh', 'huyện thạnh hóa', 'xã vĩnh hòa',
       'xã khánh thạnh tân', 'xã hương mỹ', 'huyện đồng xuân',
       'tỉnh điện biên', 'phường thảo điền', 'phường tân đông hiệp',
       'xã tam bình', 'xã an hữu', 'thị xã tân uyên', 'huyện kế sách',
       'thành phố tam điệp', 'phường an phú', 'thị trấn sa thầy',
       'xã trừ văn thố', 'thành phố tuy hòa', 'xã bình giã',
       'xã xuân đông', 'xã đông hà', 'huyện tân hồng', 'xã kiến thành',
       'xã tân hà', 'xã vũ hòa', 'phường phú lợi', 'thị xã phước long',
       'tổ 26', 'xã tân hiệp', 'huyện tuần giáo', 'xã an thạnh thủy',
       'thị trấn thủ thừa', 'xã phú lộc', 'xã thạnh tân', 'quận 8',
       'xã hòa sơn', 'thị xã buôn hồ', 'xã thiện mỹ', 'huyện tam nông',
       'phường tự an', 'thị trấn phước an', 'thị trấn long hồ',
       'xã cuor đăng', 'phường phương đông', 'huyện quỳnh lưu',
       'tỉnh quảng ninh', 'xã bắc sơn', 'phường tân thới hiệp',
       'phường phú mỹ', 'kiên giang', 'gia lai', 'vĩnh long', 'an giang',
       'thị trấn dương minh châu', 'bến tre', 'long an',
       'thị xã ninh hòa', 'xã hiếu phụng', 'xã đồng phú',
       'thị xã điện bàn', 'phường bình chuẩn', 'huyện bình lục',
       'phường 2', 'huyện tân phước', 'xã long phước',
       'phường bình chiểu', 'đắk nông', 'bình dương', 'kon tum',
       'tiền giang', 'huyện hòai nhơn', 'xã mỹ hòa', 'thị trấn vĩnh an',
       'xã vĩnh thạnh trung', 'bình định', 'phường 12', 'tỉnh lạng sơn',
       'phường tân xuân', 'phú yên', 'huyện u minh thượng', 'quảng ngãi',
       'xã tân bình thạnh', 'huyện ia grai', 'đắk lắk', 'huyện ea h\\leo',
       'khóm châu long 2', 'tây ninh', 'huyện cầu kè', 'phường cẩm thủy',
       'ấp 2', 'khánh hòa', 'thị xã đồng xòai', 'đồng nai', 'bình phước',
       'thị trấn hòa thành', 'phường tân an', 'xã bình trưng',
       'xã tân lợi thạnh', 'tp đồng xoài', 'huyện chư pưh', 'phường 22',
       'ninh thuận', 'đồng tháp', 'thị trấn đức phong', 'thái bình',
       'huyện hiệp hòa', 'xã phú lập', 'phường tân hòa', 'thừa thiên huế',
       'phường định hòa', 'xã phú lâm', 'xã nghĩa thành',
       'phường đống đa', 'quảng nam', 'huyện hòai ân', 'ninh bình',
       'xã lang minh', 'cà mau', 'huyện krông buk', 'xã tam hiệp',
       'nghệ an', 'xã phú thạnh', 'thành phố phúc yên', 'xã chà là',
       'xã liên đầm', 'thị trấn lạc tánh', 'phường uyên hưng',
       'huyện ninh hải', 'xã long điền a', 'phường phước nguyên',
       'thị trấn an phú', 'xã tân bình', 'lâm đồng', 'quảng bình',
       'huyện lệ thuỷ', 'huyện nam trực', 'phường chánh nghĩa',
       'bà rịa - vũng tàu', 'xã bảo quang', 'huyện bầu bàng',
       'phường khánh xuân', 'hà tĩnh', 'quảng trị', 'xã an cư',
       'khóm mỹ thành', 'huyện tiểu cần', 'xã bình an', 'hà nội',
       'xã lâm sơn', 'thị trấn tam bình'], dtype=object)

In [69]:
df1['diachi_tinhtp'].describe()

count                      8294
unique                      740
top       thành phố hồ chí minh
freq                       1399
Name: diachi_tinhtp, dtype: object

### Lưu dữ liệu đã làm sạch

In [70]:
df1.to_csv('data_clean/01.sinhvien.csv', index=False)

# Bảng 2. diem.xlsx

### Xử lí chung

In [71]:
# Đọc dữ liệu
df2 = pd.read_excel("Education_dataset_V2/02.diem.xlsx")
df2.head()

,id,mssv,mamh,malop,sotc,namhoc,hocky,diem,trangthai,mamh_tt
0,137424.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,CS1113,CS1113.D11,4.0,2012.0,1.0,0.0,2.0,NULL
1,140865.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,PH001,PH001.D11,4.0,2012.0,1.0,0.0,1.0,NULL
2,141624.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ENGL1113,ENGL1113.D11CTTT,3.0,2012.0,1.0,0.0,2.0,NULL
3,141651.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ADENG1,ADENG1.D11CTTT,0.0,2012.0,1.0,0.0,2.0,NULL
4,141684.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,SS001,SS001.D11CTTT,5.0,2012.0,1.0,0.0,2.0,NULL

In [72]:
# In ra các cột của bảng
df2.columns

Index(['id', 'mssv', ' mamh', ' malop', ' sotc', ' namhoc', ' hocky', ' diem',
       ' trangthai', ' mamh_tt'],
      dtype='object')

In [73]:
# Bỏ khoảng trắng ở tên cột
df2.columns = df2.columns.str.strip()
df2.columns

Index(['id', 'mssv', 'mamh', 'malop', 'sotc', 'namhoc', 'hocky', 'diem',
       'trangthai', 'mamh_tt'],
      dtype='object')

In [74]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99099 entries, 0 to 99098
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         20000 non-null  float64
 1   mssv       98963 non-null  object
 2   mamh       98963 non-null  object
 3   malop      98963 non-null  object
 4   sotc       98963 non-null  float64
 5   namhoc     98963 non-null  float64
 6   hocky      98963 non-null  float64
 7   diem       98928 non-null  float64
 8   trangthai  98963 non-null  float64
 9   mamh_tt    98963 non-null  object
dtypes: float64(6), object(4)
memory usage: 7.6+ MB

In [75]:
# Thống kê giá trị NaN ở mỗi cột
df2.isna().sum()

id           79099
mssv           136
mamh           136
malop          136
sotc           136
namhoc         136
hocky          136
diem           171
trangthai      136
mamh_tt        136
dtype: int64

In [76]:
# Loại bỏ cột id
df2.drop(columns=["id"], axis=1, inplace=True)
df2.shape

(99099, 9)

In [77]:
# Loại bỏ giá trị NaN ở tất cả các cột
df2.dropna(inplace=True)
df2.shape

(98928, 9)

### mamh

In [78]:
# Loại bỏ khoảng trắng ở 2 đầu giá trị
df2["mamh"] = df2["mamh"].str.strip()
df2["mamh"].unique()

array(['CS1113', 'PH001', 'ENGL1113', 'ADENG1', 'SS001', 'MA003', 'MA001',
       'IT001', 'PE001', 'MATH2144', 'PE002', 'SPCH3724', 'EN001',
       'MA002', 'EN002', 'ENBT', 'PH002', 'CE101', 'CE104', 'CE114',
       'IT007', 'SMET2', 'CS2133', 'ADENG2', 'IT002', 'EN003', 'SE312',
       'SE323', 'IT008', 'CS105', 'IT003', 'PH003', 'MA004', 'MA005',
       'IT004', 'IS402', 'MATH2153', 'IT005', 'IT009', 'NT307', 'SS004',
       'SE104', 'ENGL1213', 'NT116', 'ITEM1', 'SS002', 'SS003', 'IT006',
       'SE102', 'WINP1', 'CE118', 'CE103', 'CS3653', 'MATH3013', 'CS4343',
       'CS221', 'NT113', 'NT305', 'SE330', 'PHYS1114', 'NT104', 'NT106',
       'IS210', 'CE105', 'IS253', 'IE103', 'SPCH3723', 'IS232', 'IS105',
       'NT119', 'CS3443', 'CS5423', 'NT111', 'SS005', 'NT118', 'IS201',
       'CS511', 'CS106', 'SE114', 'SE106', 'NT101', 'CS406', 'IS215',
       'IS213', 'SE220', 'CE119', 'IS334', 'IE102', 'SC203', 'PHYS1214',
       'SE332', 'SE107', 'IS254', 'NT334', 'CS4793', 'CE222', 'IS207',
       'IS216', 'EN004', 'EN005', 'CE404', 'IE104', 'NT112', 'NT105',
       'IE105', 'CS3373', 'STAT4033', 'NT103', 'SE101', 'CS111', 'SE341',
       'IS251', 'SE215', 'CS112', 'CS110', 'NT503', 'CE117', 'CS4283',
       'NT130', 'SE301', 'NT206', 'CS313', 'NT204', 'NT131', 'NT201',
       'SE340', 'NT208', 'NT109', 'CS214', 'IS336', 'IS403', 'NT331',
       'EC202', 'IS208', 'CS217', 'IS217', 'SE346', 'SE100', 'IS353',
       'EC203', 'SE108', 'IE106', 'CS4323', 'NT330', 'CS3363', 'CS519',
       'SE111', 'EN006', 'EC201', 'NT332', 'CE107', 'NT209', 'NT333',
       'IS252', 'IS211', 'CE315', 'CE212', 'CE221', 'CE316', 'MSIS4523',
       'CS4243', 'MSIS3303', 'NT303', 'IE303', 'EC302', 'SE334', 'IE101',
       'NT405', 'CS314', 'SE313', 'CS211', 'CS113', 'CS521', 'CS2433',
       'SE325', 'CS524', 'CS226', 'CS326', 'SE109', 'CS412', 'NT205',
       'SE310', 'CS4273', 'SE214', 'SE331', 'CS316', 'NT114', 'NT117',
       'EC301', 'EC001', 'CS301', 'IS212', 'CS3613', 'NT115', 'CS5433',
       'IE202', 'CE211', 'CS3423', 'NT402', 'NT211', 'IS335', 'CS5030',
       'NT532', 'CS409', 'ADENG3', 'NT210', 'CS222', 'CS323', 'CS325',
       'CS410', 'IS405', 'SE221', 'MSIS3033', 'IE206', 'NT406', 'CE401',
       'IS219', 'SE501', 'CS420', 'CS315', 'SE112', 'CE201', 'CE326',
       'CS302', 'IE403', 'MSIS4263'], dtype=object)

In [79]:
df2["mamh"].describe()

count     98928
unique      226
top       MA001
freq       4775
Name: mamh, dtype: object

### malop

In [80]:
# Loại bỏ khoảng trắng ở 2 đầu giá trị
df2["malop"] = df2["malop"].str.strip()
df2["malop"].unique()

array(['CS1113.D11', 'PH001.D11', 'ENGL1113.D11CTTT', ..., 'IS207.H22',
       'MSIS4263.H21.CTTT', 'IT005.H21'], dtype=object)

In [81]:
df2["malop"].describe()

count         98928
unique         1960
top       SS001.E15
freq            214
Name: malop, dtype: object

### mamh_tt

In [82]:
df2["mamh_tt"].value_counts()

 NULL)       78780
 NULL        20001
 NULL);        135
 'EN002')        4
 'EN003')        4
 'EN005')        1
 'SE107')        1
 'CS105')        1
 'NT103')        1
Name: mamh_tt, dtype: int64

In [83]:
df2[df2["mamh_tt"]== " 'NT103')"]

,mssv,mamh,malop,sotc,namhoc,hocky,diem,trangthai,mamh_tt
90062,F1E5E055XPvAibaEXe+Wjq/eoSKNhdg9exGKekXz,NT131,NT131.H11.ANTN,4.0,2016.0,1.0,7.0,1.0,'NT103')

In [84]:
# Loại bỏ cột mamh_tt vì thông tin không cần thiết, quá ít thông tin
df2.drop(columns=["mamh_tt"], axis=1, inplace=True)

### Lưu dữ liệu đã làm sạch

In [85]:
df2.to_csv('data_clean/02.diem.csv', index=False)

# Bảng 3. sinhvien_chungchi.xlsx

### Xử lí chung

In [86]:
# Đọc dữ liệu
df3 = pd.read_excel("Education_dataset_V2/03.sinhvien_chungchi.xlsx")
df3.head()

,id,mssv,ngaythi,url,loaixn,url_1,loaixn_2,listening,speaking,reading,writing,tongdiem,lydo,trangthai,ngayxl,Column1
0,6.0,12C24162XPvAibaEXe9Xnw4t0GPgx9K2sCLXkxKl,NaN,bangcap/13521066/13521066_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:56:09,NaT,NaN,NaN
1,8.0,9095EEE4XPvAibaEXe93PEySAJOVk2kOrJQCpxlr,NaN,bangcap/13520021/13520021_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:15,NaT,NaN,NaN
2,13.0,538FDEFEXPvAibaEXe9P07hcrvmhCe3unM2XvNXE,NaN,bangcap/13520066/13520066_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:27,NaT,NaN,NaN
3,14.0,82EB45E9XPvAibaEXe9eSUilQ3V71rLMOFZnU1bQ,NaN,bangcap/13520828/13520828_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:56:00,NaT,NaN,NaN
4,15.0,DDB9E00CXPvAibaEXe/Xn8KZjn44cdZNDzzd5bIQ,NaN,bangcap/13520576/13520576_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:51,NaT,NaN,NaN

In [87]:
# In ra các cột của bảng
df3.columns

Index(['id', 'mssv', ' ngaythi', ' url', ' loaixn', ' url_1', ' loaixn_2',
       ' listening', ' speaking', ' reading', ' writing', ' tongdiem', ' lydo',
       ' trangthai', ' ngayxl', 'Column1'],
      dtype='object')

In [88]:
# Bỏ khoảng trắng ở tên cột
df3.columns = df3.columns.str.strip()
df3.columns

Index(['id', 'mssv', 'ngaythi', 'url', 'loaixn', 'url_1', 'loaixn_2',
       'listening', 'speaking', 'reading', 'writing', 'tongdiem', 'lydo',
       'trangthai', 'ngayxl', 'Column1'],
      dtype='object')

In [89]:
df3["Column1"].value_counts()

 2021-03-11 09:00:33      1
 '2021-03-11 09:00:33'    1
Name: Column1, dtype: int64

In [90]:
# Các cột có giá trị không phù hợp với ý nghĩa của cột
df3[['url_1', 'loaixn_2', 'listening', 'speaking', 'reading', 'writing', 'tongdiem', 'lydo']]

,url_1,loaixn_2,listening,speaking,reading,writing,tongdiem,lydo
0,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:56:09
1,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:15
2,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:27
3,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:56:00
4,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:51
...,...,...,...,...,...,...,...,...
3395,490.0,NaN,490.0,NaN,'980',NaN,0,NaN
3396,310.0,NaN,250.0,NaN,'560',NaN,0,NaN
3397,395.0,NaN,260.0,NaN,'655',NaN,0,NaN
3398,NaN,NaN,NaN,NaN,'269',NaN,0,NaN
3399,NaN,NaN,NaN,NaN,'7.0',NaN,0,NULL);

In [91]:
df3[['listening', 'speaking', 'reading', 'writing', 'tongdiem', 'lydo', 'trangthai', 'ngayxl']]

,listening,speaking,reading,writing,tongdiem,lydo,trangthai,ngayxl
0,NaN,NaN,NaN,,1,2017-09-08 13:56:09,NaT,NaN
1,NaN,NaN,NaN,,1,2017-09-08 13:55:15,NaT,NaN
2,NaN,NaN,NaN,,1,2017-09-08 13:55:27,NaT,NaN
3,NaN,NaN,NaN,,1,2017-09-08 13:56:00,NaT,NaN
4,NaN,NaN,NaN,,1,2017-09-08 13:55:51,NaT,NaN
...,...,...,...,...,...,...,...,...
3395,490.0,NaN,'980',NaN,0,NaN,NaT,NaN
3396,250.0,NaN,'560',NaN,0,NaN,NaT,NaN
3397,260.0,NaN,'655',NaN,0,NaN,NaT,NaN
3398,NaN,NaN,'269',NaN,0,NaN,NaT,NaN
3399,NaN,NaN,'7.0',NaN,0,NULL);,NaT,NaN

In [92]:
# Dịch chuyển các cột sang phải 2 đơn vị
df3[['listening', 'speaking', 'reading', 'writing', 'tongdiem', 'lydo', 'trangthai', 'ngayxl']] = df3[['url_1', 'loaixn_2', 'listening', 'speaking', 'reading', 'writing', 'tongdiem', 'lydo']]
df3

,id,mssv,ngaythi,url,loaixn,url_1,loaixn_2,listening,speaking,reading,writing,tongdiem,lydo,trangthai,ngayxl,Column1
0,6.0,12C24162XPvAibaEXe9Xnw4t0GPgx9K2sCLXkxKl,NaN,bangcap/13521066/13521066_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:56:09,NaN
1,8.0,9095EEE4XPvAibaEXe93PEySAJOVk2kOrJQCpxlr,NaN,bangcap/13520021/13520021_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:15,NaN
2,13.0,538FDEFEXPvAibaEXe9P07hcrvmhCe3unM2XvNXE,NaN,bangcap/13520066/13520066_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:27,NaN
3,14.0,82EB45E9XPvAibaEXe9eSUilQ3V71rLMOFZnU1bQ,NaN,bangcap/13520828/13520828_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:56:00,NaN
4,15.0,DDB9E00CXPvAibaEXe/Xn8KZjn44cdZNDzzd5bIQ,NaN,bangcap/13520576/13520576_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:51,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395,4561.0,53BB8D1AXPvAibaEXe9Fy2hCq9OiA55gkkbklho/,'2021-04-22','bangcap/17521132/17521132_bangcap_TOEIC_LR_2...,'TOEIC_LR',490.0,NaN,490.0,NaN,490.0,NaN,'980',NaN,0,NaN,NaN
3396,4562.0,7075BE69XPvAibaEXe8WdGcsQTF3yHQhmzrDl1Yc,'2021-05-21','bangcap/14520706/14520706_bangcap_TOEIC_LR_2...,'TOEIC_LR',310.0,NaN,310.0,NaN,250.0,NaN,'560',NaN,0,NaN,NaN
3397,4563.0,063FA88DXPvAibaEXe+ItThaeWSaTndzLvy0hCWF,'2021-04-24','bangcap/17521281/17521281_bangcap_TOEIC_LR_2...,'TOEIC_LR',395.0,NaN,395.0,NaN,260.0,NaN,'655',NaN,0,NaN,NaN
3398,4565.0,EC99A310XPvAibaEXe9F2tx/ToPx3H/qqDPJ7QaV,'2021-03-20','bangcap/16520846/16520846_bangcap_VNU-EPT_20...,'VNU-EPT',NaN,NaN,NaN,NaN,NaN,NaN,'269',NaN,0,NaN,NaN
3399,4569.0,609F9309XPvAibaEXe9R53Fu3buHyTgw/++uttLg,'2021-05-22','bangcap/17520563/17520563_bangcap_IELTS_2021...,'IELTS',NaN,NaN,NaN,NaN,NaN,NaN,'7.0',NaN,0,NULL);,NaN

In [93]:
# Xóa các cột thừa sau khi dịch chuyển giá trị các cột
df3 = df3.drop(['url_1', 'loaixn_2'], axis=1)
df3

,id,mssv,ngaythi,url,loaixn,listening,speaking,reading,writing,tongdiem,lydo,trangthai,ngayxl,Column1
0,6.0,12C24162XPvAibaEXe9Xnw4t0GPgx9K2sCLXkxKl,NaN,bangcap/13521066/13521066_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:56:09,NaN
1,8.0,9095EEE4XPvAibaEXe93PEySAJOVk2kOrJQCpxlr,NaN,bangcap/13520021/13520021_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:15,NaN
2,13.0,538FDEFEXPvAibaEXe9P07hcrvmhCe3unM2XvNXE,NaN,bangcap/13520066/13520066_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:27,NaN
3,14.0,82EB45E9XPvAibaEXe9eSUilQ3V71rLMOFZnU1bQ,NaN,bangcap/13520828/13520828_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:56:00,NaN
4,15.0,DDB9E00CXPvAibaEXe/Xn8KZjn44cdZNDzzd5bIQ,NaN,bangcap/13520576/13520576_bangcap_TOIEC_20170...,TOIEC,NaN,NaN,NaN,NaN,NaN,,1,2017-09-08 13:55:51,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395,4561.0,53BB8D1AXPvAibaEXe9Fy2hCq9OiA55gkkbklho/,'2021-04-22','bangcap/17521132/17521132_bangcap_TOEIC_LR_2...,'TOEIC_LR',490.0,NaN,490.0,NaN,'980',NaN,0,NaN,NaN
3396,4562.0,7075BE69XPvAibaEXe8WdGcsQTF3yHQhmzrDl1Yc,'2021-05-21','bangcap/14520706/14520706_bangcap_TOEIC_LR_2...,'TOEIC_LR',310.0,NaN,250.0,NaN,'560',NaN,0,NaN,NaN
3397,4563.0,063FA88DXPvAibaEXe+ItThaeWSaTndzLvy0hCWF,'2021-04-24','bangcap/17521281/17521281_bangcap_TOEIC_LR_2...,'TOEIC_LR',395.0,NaN,260.0,NaN,'655',NaN,0,NaN,NaN
3398,4565.0,EC99A310XPvAibaEXe9F2tx/ToPx3H/qqDPJ7QaV,'2021-03-20','bangcap/16520846/16520846_bangcap_VNU-EPT_20...,'VNU-EPT',NaN,NaN,NaN,NaN,'269',NaN,0,NaN,NaN
3399,4569.0,609F9309XPvAibaEXe9R53Fu3buHyTgw/++uttLg,'2021-05-22','bangcap/17520563/17520563_bangcap_IELTS_2021...,'IELTS',NaN,NaN,NaN,NaN,'7.0',NaN,0,NULL);,NaN

In [94]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         3390 non-null   float64
 1   mssv       3390 non-null   object
 2   ngaythi    2856 non-null   object
 3   url        3390 non-null   object
 4   loaixn     3390 non-null   object
 5   listening  2298 non-null   float64
 6   speaking   288 non-null    float64
 7   reading    2296 non-null   float64
 8   writing    288 non-null    float64
 9   tongdiem   2086 non-null   object
 10  lydo       2438 non-null   object
 11  trangthai  3390 non-null   object
 12  ngayxl     2616 non-null   object
 13  Column1    2 non-null      object
dtypes: float64(5), object(9)
memory usage: 372.0+ KB

In [95]:
# Thống kê giá trị NaN ở mỗi cột
df3.isna().sum()

id             10
mssv           10
ngaythi       544
url            10
loaixn         10
listening    1102
speaking     3112
reading      1104
writing      3112
tongdiem     1314
lydo          962
trangthai      10
ngayxl        784
Column1      3398
dtype: int64

In [96]:
df3.drop(columns=["Column1"], inplace=True)

In [97]:
df3.dropna(subset=['mssv'], axis=0, inplace=True)
df3.isna().sum()

id              0
mssv            0
ngaythi       534
url             0
loaixn          0
listening    1092
speaking     3102
reading      1094
writing      3102
tongdiem     1304
lydo          952
trangthai       0
ngayxl        774
dtype: int64

###ngaythi

In [98]:
# Loại bỏ khoảng trắng ở 2 đầu giá trị và kí tự '
df3["ngaythi"] = df3["ngaythi"].str.strip().str.replace("'", '', regex=True)
df3["ngaythi"].unique()

array([nan, '2010-06-21', '2018-03-11', '2017-11-07', '2018-04-04',
       '2012-01-06', '2018-05-11', '2017-12-03', '2018-05-12',
       '2018-05-14', '2018-05-17', '2017-12-07', '2018-05-16',
       '2018-05-19', '2018-06-01', '2013-08-28', '2017-02-08',
       '2017-12-11', '2018-03-05', '2010-04-06', '2017-09-28',
       '2018-05-24', '2017-09-08', '2012-01-16', '2014-03-04',
       '2017-08-12', '2017-06-15', '2015-04-16', '2018-07-01',
       '2018-02-03', '2018-08-18', '2018-05-27', '2018-08-22',
       '2018-08-04', '2018-06-29', '2018-06-12', '2018-04-19',
       '2018-08-25', '2018-09-07', '2018-09-04', '2016-11-22',
       '2018-06-14', '2018-09-08', '2016-12-03', '2018-09-29',
       '2018-06-10', '2016-06-14', '2018-10-19', '2018-10-06',
       '2018-10-11', '2018-04-17', '2018-10-09', '2011-01-19',
       '2016-12-17', '2018-10-17', '2018-09-28', '2017-11-22',
       '2018-10-14', '2018-11-13', '2018-11-17', '2010-10-13',
       '2018-11-18', '2018-09-14', '2018-11-30', '2018-03-25',
       '2018-12-01', '2018-11-04', '2018-12-02', '2018-09-24',
       '2018-11-23', '2017-04-22', '2018-12-15', '2018-11-27',
       '2014-07-23', '2018-10-20', '2018-12-22', '2018-12-25',
       '2018-12-23', '2018-12-29', '2019-01-23', '2017-11-25',
       '2017-09-26', '2019-01-17', '2012-02-16', '2018-04-12',
       '2017-07-05', '2018-11-25', '2014-05-19', '2018-11-10',
       '2017-04-24', '2019-01-06', '2018-04-05', '2019-01-27',
       '2017-04-26', '2018-12-13', '2019-02-15', '2018-11-19',
       '2018-08-11', '2018-08-05', '2018-03-26', '2018-03-03',
       '2018-01-31', '2012-05-26', '2019-02-21', '2018-06-18',
       '2018-03-24', '2018-12-10', '2019-02-14', '2018-07-11',
       '2013-07-20', '2019-02-09', '2018-11-02', '2019-01-22',
       '2011-07-26', '2012-08-09', '2019-12-15', '2019-12-29',
       '2019-02-23', '2017-10-02', '2014-06-27', '2018-04-22',
       '2017-03-30', '2019-03-17', '2019-03-09', '2011-06-13',
       '2012-08-14', '2018-02-02', '2019-04-07', '2012-08-01',
       '2018-10-26', '2019-04-21', '2019-04-06', '2019-04-27',
       '2019-01-21', '2019-01-16', '2019-04-20', '2014-04-05',
       '2019-05-11', '2019-04-26', '2019-05-22', '2019-05-25',
       '2019-05-24', '2018-01-20', '2019-06-02', '2019-05-04',
       '2019-05-18', '2019-05-27', '2019-05-28', '2019-05-17',
       '2019-06-16', '2019-05-09', '2019-06-23', '2019-06-09',
       '2019-06-29', '2019-04-24', '2019-05-29', '2019-07-29',
       '2019-07-28', '2019-07-31', '2019-07-30', '2018-12-06',
       '2019-06-27', '2018-12-20', '2019-07-13', '2018-12-08',
       '2018-07-28', '2018-01-13', '2019-08-10', '2019-08-04',
       '2019-08-06', '2019-05-02', '2019-08-14', '2019-08-16',
       '2019-08-18', '2019-07-12', '2017-09-09', '2019-08-19',
       '2019-05-07', '2019-01-05', '2019-07-24', '2018-11-26',
       '2018-12-24', '2019-07-27', '2019-08-08', '2019-08-24',
       '2019-08-30', '2019-08-27', '2019-07-14', '2019-09-08',
       '2019-09-04', '2019-08-25', '2017-11-02', '2019-08-28',
       '2019-09-11', '2018-08-02', '2019-05-23', '2019-09-13',
       '2019-08-02', '2019-09-21', '2019-09-29', '2019-09-22',
       '2019-09-28', '2019-09-30', '2019-10-13', '2018-09-09',
       '2019-10-16', '2019-10-05', '2019-10-20', '2019-10-22',
       '2019-10-06', '2019-10-27', '2019-11-08', '2019-11-03',
       '2019-11-07', '2019-11-10', '2019-07-07', '2019-11-15',
       '2019-10-26', '2019-11-16', '2019-08-29', '2019-11-12',
       '2018-10-02', '2019-10-25', '2019-11-04', '2019-07-26',
       '2019-10-23', '2019-11-20', '2019-10-19', '2019-11-26',
       '2019-01-20', '2019-11-13', '2019-11-24', '2019-11-09',
       '2019-10-09', '2019-11-27', '2019-11-21', '2018-10-18',
       '2019-11-02', '2019-10-04', '2019-12-02', '2019-11-19',
       '2019-11-29', '2019-12-09', '2019-12-13', '2019-12-06',
       '2019-12-07', '2019-05-19', '2019-12-22', '2019-12-20',
       '2019-11-30', '2019-12-23', '2019-12-27', '2019-12-16',
       '2018-08-13', '2020-01-03', '2019-12-28', '2019-12-12',
       '2019-12-14', '2020-01-04', '2020-01-19', '2020-01-31',
       '2019-12-01', '2020-02-22', '2020-03-08', '2019-12-08',
       '2020-03-18', '2019-08-22', '2020-03-19', '2019-01-01',
       '2020-02-16', '2020-05-10', '2020-05-11', '2020-05-16',
       '2019-06-13', '2020-05-06', '1999-12-28', '2020-05-13',
       '2020-05-14', '2020-02-10', '2020-05-09', '2020-01-18',
       '2019-01-25', '2019-03-21', '2020-05-22', '2020-03-01',
       '2020-03-07', '2020-02-08', '2020-02-29', '2019-11-28',
       '2019-03-20', '2019-05-26', '2020-01-05', '2020-05-23',
       '2020-05-30', '2019-02-13', '2020-05-24', '2020-05-29',
       '2019-09-07', '2020-03-14', '2019-09-14', '2019-09-19',
       '2020-05-21', '2020-05-25', '2019-06-24', '2020-06-13',
       '2020-06-11', '2020-06-17', '2020-06-19', '2019-09-15',
       '2020-06-26', '2020-06-20', '2020-06-21', '2020-06-15',
       '2020-06-22', '2020-06-24', '2020-06-14', '2019-03-29',
       '2020-06-28', '2020-06-23', '2020-07-01', '2020-05-20',
       '2020-02-20', '2019-05-20', '2019-11-23', '2020-06-30',
       '2019-12-19', '2020-07-06', '2020-07-05', '2020-07-04',
       '2020-07-10', '2000-01-19', '2019-08-20', '2020-07-20',
       '2020-07-12', '2020-07-14', '2000-07-14', '2018-08-16',
       '2020-07-11', '2020-07-19', '2020-01-30', '2020-07-23',
       '2019-10-18', '2019-11-22', '2020-06-07', '2020-07-24',
       '2020-07-22', '2020-07-25', '2020-07-26', '2020-06-04',
       '2020-07-09', '2020-08-01', '2016-08-04', '2020-08-03',
       '2020-08-09', '2020-08-08', '2020-08-04', '2020-07-18',
       '2020-01-21', '2014-07-06', '2020-08-10', '2020-08-12',
       '2020-07-21', '2019-02-01', '2020-08-20', '2020-06-02',
       '2018-12-18', '2020-08-02', '2020-08-21', '2020-08-15',
       '2020-08-22', '2020-07-16', '2020-08-26', '2020-08-19',
       '2020-08-23', '2000-08-03', '2020-08-29', '2020-09-11',
       '2020-09-12', '2020-09-16', '2020-09-18', '2020-09-15',
       '2020-09-13', '2020-08-30', '2020-09-19', '2020-09-20',
       '2019-01-12', '2020-09-27', '2020-07-31', '2020-09-24',
       '2020-09-25', '2017-06-01', '2018-12-14', '2020-08-14',
       '2020-09-23', '2020-09-26', '2020-09-30', '2020-08-16',
       '2020-03-05', '2020-01-22', '2020-03-15', '2020-08-28',
       '2020-09-03', '2020-10-12', '2020-10-11', '2020-10-14',
       '2020-10-22', '2020-10-16', '2020-10-13', '2020-10-18',
       '2020-09-29', '2020-10-21', '2018-04-15', '2020-10-31',
       '2020-10-19', '2020-10-24', '2020-10-25', '2020-10-27',
       '2020-11-02', '2020-11-01', '2020-11-04', '2020-10-23',
       '2020-11-08', '2020-09-28', '2020-10-04', '2020-11-09',
       '2020-11-11', '2020-11-05', '2020-10-20', '2020-11-12',
       '2020-11-06', '2020-11-14', '2019-11-18', '2020-11-15',
       '2018-12-11', '2020-11-17', '2020-11-16', '2020-11-18',
       '2020-11-13', '2020-11-19', '2020-11-20', '2020-10-30',
       '2020-11-22', '2020-11-23', '2020-11-25', '2020-10-08',
       '2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30',
       '2020-12-03', '2020-02-15', '2020-12-06', '2020-12-07',
       '2020-12-05', '2020-12-11', '2020-12-04', '2020-12-21',
       '2020-12-12', '2020-12-17', '2020-12-19', '2020-12-20',
       '2020-12-26', '2020-12-27', '2021-12-21', '2021-01-05',
       '2020-12-24', '2020-12-28', '2020-12-30', '2020-12-31',
       '2021-01-06', '2020-10-07', '2020-11-26', '2021-01-04',
       '2021-01-09', '2020-02-07', '2021-01-10', '2021-01-07',
       '2021-01-18', '2020-12-02', '2021-01-16', '2019-03-23',
       '2021-01-17', '2021-01-22', '2021-01-13', '2020-10-28',
       '2021-01-24', '2021-01-27', '2020-01-20', '2021-01-20',
       '2021-01-23', '2021-01-29', '2021-02-06', '2021-01-26',
       '2021-02-01', '2021-01-28', '2021-01-30', '2021-01-31',
       '2016-03-01', '2021-01-14', '2020-12-25', '2021-02-20',
       '2021-02-07', '2021-02-05', '2019-03-07', '2021-02-04',
       '2021-02-17', '2020-12-13', '2021-02-24', '2021-01-25',
       '2021-02-25', '2020-03-12', '2021-03-07', '2021-02-19',
       '2021-12-06', '2021-02-27', '2021-03-11', '2021-03-12',
       '2021-03-18', '2021-03-20', '2021-03-10', '2021-03-17',
       '2021-03-21', '2021-03-27', '2021-03-23', '2021-03-26',
       '2021-03-13', '2021-03-06', '2021-03-31', '2021-01-02',
       '2021-03-25', '2021-03-24', '2021-04-03', '2021-04-04',
       '2021-04-08', '2021-04-11', '2021-03-28', '2021-04-14',
       '2021-04-17', '2020-12-22', '2021-03-14', '2021-04-18',
       '2021-04-19', '2021-04-12', '2021-04-10', '2021-04-26',
       '2021-04-23', '2020-11-07', '2020-12-16', '2021-04-25',
       '2021-04-29', '2021-04-24', '2021-05-05', '2021-05-07',
       '2021-05-08', '2021-05-13', '2021-05-20', '2021-05-22',
       '2021-04-22', '2021-05-21'], dtype=object)

In [99]:
df3["ngaythi"].describe()

count           2856
unique           558
top       2018-12-29
freq             150
Name: ngaythi, dtype: object

###loaixn

In [100]:
df3["loaixn"].unique()

array([' TOIEC', 'TOEIC_LR', ' VNU-EPT', ' IELTS', ' NHAT', ' Cambrigde',
       'TOEIC_SW', ' TOEFL iBT', ' PHAP', ' DGNL', " 'TOEIC_LR'",
       " 'IELTS'", " 'TOEIC_SW'", " 'VNU-EPT'", " 'Cambrigde'",
       " 'TOIEC'", " 'NHAT'", " 'TOEFL iBT'", " 'PHAP'", " 'DGNL'"],
      dtype=object)

In [101]:
# Loại bỏ khoảng trắng ở 2 đầu giá trị và kí tự '
df3["loaixn"] = df3["loaixn"].str.strip().str.replace("'", '', regex=True)
df3["loaixn"].unique()

array(['TOIEC', 'TOEIC_LR', 'VNU-EPT', 'IELTS', 'NHAT', 'Cambrigde',
       'TOEIC_SW', 'TOEFL iBT', 'PHAP', 'DGNL'], dtype=object)

###lydo

In [102]:
# Loại bỏ khoảng trắng ở 2 đầu giá trị và kí tự '
df3["lydo"] = df3["lydo"].str.strip().str.replace("'", '', regex=True)
df3["lydo"].unique()

array(['', 'Đạt chuẩn đầu ra', 'Miễn Anh văn 3',
       'Miễn Anh văn 3 và đạt chuẩn đầu ra', 'Miễn AV2', 'Miễn Anh văn 1',
       'Được Miễn AV1', 'SV đạt chuẩn đầu ra',
       'Chứng chỉ hợp lệ và đạt chuẩn quá trình nhưng sinh viên vẫn phải học anh văn 1.',
       'Chứng chỉ hợp lệ nhưng chứng chỉ này không đạt số điểm theo quy định để được xét tốt nghiệp và xét miễn anh văn',
       'Xác minh với TTNN', 'Chứng chỉ quá hạn',
       'Sinh viên phải úp hình chứng chỉ hoặc phiếu điểm ngoại ngữ.',
       'Em vui lòng cung cấp ID Number và Password mới xác minh được',
       'Vui lòng úp hình chứng chỉ của em.',
       'Vui lòng cập nhật hình chứng chỉ có thông tin cá nhân của em trong đó.',
       'Sinh viên vui lòng up lại chứng chỉ',
       'Chứng chỉ này không dùng để xét tốt nghiệp.',
       'Chứng chỉ đã làm lại kết quả điểm', 'Ngày thi 29/12/2018',
       'Không đủ điểm xét tốt nghiệp.',
       'Sinh viên vui lòng up chứng chỉ.',
       'Chứng nhận không dùng cho chuẩn đầu ra để xét tốt nghiệp.',
       'Chứng chỉ quá hạn tại thời điểm kiểm tra.', nan,
       'Chứng chỉ đã quá hạn tại thời điểm xét.',
       'Sinh viên vui lòng cập nhật hình chứng chỉ.',
       'Sinh viên vui lòng up hình chứng chỉ.',
       'Chứng nhận không được dùng xét tốt nghiệp.',
       'Chứng chỉ quá thời hạn xét miễn',
       'Chứng chỉ đã quá hạn 2 năm tại thời điểm xét.',
       'Chứng nhận không được dùng để xét chuẩn đầu ra.',
       'Chứng chỉ không đạt yêu cầu chuẩn đầu ra theo quy định.',
       'Chứng chỉ này là chứng chỉ Đánh giá năng lực',
       'Chứng nhận không được xét chuẩn đầu ra.',
       'Chứng chỉ không đúng theo quy định ngoại ngữ.',
       'Chứng chỉ đã quá hạn 02 năm tại thời điểm sinh viên cập nhật lên trang daa.uit.edu.vn',
       'Sinh viên lưu ý chọn đúng loại chứng chỉ là đánh giá năng lực',
       'Sinh viên vui lòng chọn đúng loại chứng chỉ: Đánh giá năng lực',
       'Đã xác nhận sinh viên nộp chứng chỉ năm 2016',
       'Chứng chỉ Đánh giá năng lực', 'Chứng chỉ ĐGNL',
       'Đánh giá năng lực',
       'Sinh viên vui lòng cung cấp số báo danh mới kiểm tra được.',
       'Miễn Anh văn 3 '], dtype=object)

###trangthai

In [103]:
# Loại bỏ khoảng trắng ở 2 đầu giá trị và kí tự '
df3["trangthai"] = df3["trangthai"].str.strip().str.replace("'", '', regex=True)
df3["trangthai"].unique()

array(['1', '3 và Đạt chuẩn đầu ra', '2', '-1',
       'hiện tại hình chụp không rõ nên không kiểm tra được thông tin.',
       'điểm chính xác là 240.', '0',
       'sinh viên vui lòng chọn lại loại chứng chỉ', 'sv được miễn AVSC',
       'không phảiTOEIC'], dtype=object)

###ngayxeploai

In [104]:
df3["ngayxl"].unique()

array([' 2017-09-08 13:56:09', ' 2017-09-08 13:55:15',
       ' 2017-09-08 13:55:27', ..., " '2021-05-14 15:31:31'",
       " '2021-05-19 11:01:24'", " '2021-05-21 14:18:25'"], dtype=object)

In [105]:
# Loại bỏ khoảng trắng ở 2 đầu giá trị và kí tự '
df3["ngayxl"] = df3["ngayxl"].str.strip().str.replace("'", '', regex=True)
df3["ngayxl"].unique()

array(['2017-09-08 13:56:09', '2017-09-08 13:55:15',
       '2017-09-08 13:55:27', ..., '2021-05-21 14:18:25',
       '2021-05-31 10:29:07', '2021-05-21 14:15:12'], dtype=object)

### Lưu dữ liệu đã làm sạch (chưa xử lí các giá trị điểm bị thiếu)

In [106]:
df3.to_csv('data_clean/03.sinhvien_chungchi.csv', index=False)

#Bảng 4. xeploaiav.xlsx

##Xử lý chung

In [107]:
# Đọc dữ liệu
df4 = pd.read_excel("Education_dataset_V2/04.xeploaiav.xlsx")
df4.head()

,id,mssv,listening,reading,total,mamh,ghichu
0,1.0,DA75FFFEXPvAibaEXe8808q51BnmQhHT8REwWMQJ,NULL,NULL,15.0,NULL,NULL
1,2.0,336B9F53XPvAibaEXe/jd8ghaf1GTNPSHNuhAHTZ,NULL,NULL,15.0,NULL,NULL
2,3.0,67A51DC3XPvAibaEXe/7YVAxOsMwOtCFvKInEQ0e,NULL,NULL,16.0,NULL,NULL
3,4.0,387E2EFEXPvAibaEXe96K1aB3B4cKSj8mKKciukN,NULL,NULL,16.0,NULL,NULL
4,6.0,13D900A2XPvAibaEXe97wmuqTYuV7bJOKimbzKxM,NULL,NULL,18.0,NULL,NULL

In [108]:
# In ra các cột của bảng
df4.columns

Index(['id', 'mssv', ' listening', ' reading', ' total', ' mamh', ' ghichu'], dtype='object')

In [109]:
# Bỏ khoảng trắng ở tên cột
df4.columns = df4.columns.str.strip()
df4.columns

Index(['id', 'mssv', 'listening', 'reading', 'total', 'mamh', 'ghichu'], dtype='object')

In [110]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6349 entries, 0 to 6348
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         6343 non-null   float64
 1   mssv       6343 non-null   object
 2   listening  6343 non-null   object
 3   reading    6343 non-null   object
 4   total      6343 non-null   float64
 5   mamh       6343 non-null   object
 6   ghichu     6343 non-null   object
dtypes: float64(2), object(5)
memory usage: 347.3+ KB

In [111]:
# Thống kê giá trị NaN ở mỗi cột
df4.isna().sum()

id           6
mssv         6
listening    6
reading      6
total        6
mamh         6
ghichu       6
dtype: int64

In [112]:
#Xoá các dòng có giá trị NaN
df4 = df4.dropna()
df4.isna().sum()

id           0
mssv         0
listening    0
reading      0
total        0
mamh         0
ghichu       0
dtype: int64

##listening and reading

In [113]:
df4['listening'] = df4['listening'].replace(' NULL', '0')
df4['reading'] = df4['reading'].replace(' NULL', '0')

In [114]:
df4['listening'] = df4['listening'].astype(float)
df4['reading'] = df4['reading'].astype(float)
df4['total'] = df4['total'].astype(float)

In [115]:
#thay thế các giá trị bị thiếu bằng total/2
df4['total'] = df4['total'].replace(0, np.nan)
df4['listening'] = df4['listening'].replace(0, np.nan)
df4['listening'] = df4['listening'].fillna(round(df4['total'].floordiv(2)))

In [116]:
df4['reading'] = df4['reading'].replace(0, np.nan)
df4['reading'] = df4['reading'].fillna(df4['total'] - df4['listening'])

In [117]:
df4

,id,mssv,listening,reading,total,mamh,ghichu
0,1.0,DA75FFFEXPvAibaEXe8808q51BnmQhHT8REwWMQJ,7.0,8.0,15.0,NULL,NULL
1,2.0,336B9F53XPvAibaEXe/jd8ghaf1GTNPSHNuhAHTZ,7.0,8.0,15.0,NULL,NULL
2,3.0,67A51DC3XPvAibaEXe/7YVAxOsMwOtCFvKInEQ0e,8.0,8.0,16.0,NULL,NULL
3,4.0,387E2EFEXPvAibaEXe96K1aB3B4cKSj8mKKciukN,8.0,8.0,16.0,NULL,NULL
4,6.0,13D900A2XPvAibaEXe97wmuqTYuV7bJOKimbzKxM,9.0,9.0,18.0,NULL,NULL
...,...,...,...,...,...,...,...
6344,6383.0,E8A5FA8CXPvAibaEXe/31hnRTOucclruvJrLqfHH,27.0,32.0,59.0,ENG01,NULL
6345,6384.0,B3487295XPvAibaEXe8iDpfibljbVHQ0k0Q2Ad15,28.0,41.0,69.0,ENG02,NULL
6346,6385.0,9166AE22XPvAibaEXe+V8Z3g2JN9F+ODXiTHI+x2,27.0,44.0,71.0,ENG02,NULL
6347,6386.0,2A792560XPvAibaEXe9gkNN06c3nLV4jpNl00QZq,30.0,26.0,56.0,ENG01,NULL
6348,6387.0,E95089F0XPvAibaEXe9S88+OcosOZnhlddS60pjv,33.0,46.0,79.0,ENG03,NULL);

In [118]:
df4 = df4.dropna()

##mamh

In [119]:
df4['mamh'] = df4['mamh'].str.strip()
df4['mamh'].unique()

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\1184360612.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['mamh'] = df4['mamh'].str.strip()

array(['NULL', 'AVSC', 'EN001', 'EN002', 'ENG01', 'ENG02', 'ENG03',
       'ENG05', 'ENG04', 'AVSC1', 'AVSC2', 'Miễn ENG03', ''], dtype=object)

In [120]:
#format lại mã lớp tiếng anh
df4['mamh'] = df4['mamh'].replace('EN001','ENG01')
df4['mamh'] = df4['mamh'].replace('EN002','ENG02')
df4['mamh'] = df4['mamh'].replace('AVSC','AVSC1')
df4['mamh'] = df4['mamh'].replace('','NULL')

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\1902455585.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['mamh'] = df4['mamh'].replace('EN001','ENG01')
C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\1902455585.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['mamh'] = df4['mamh'].replace('EN002','ENG02')
C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\1902455585.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['mamh'] = df4['mamh'].replace('AVSC','AVSC1')
C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\1902455585.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['mamh'] = df4['mamh'].replace('','NULL')

In [121]:
df4['mamh'] = df4['mamh'].where(df4['mamh'] != 'NULL', 
                              pd.cut(df4['total'], [0, 26, 40, 60, 70, 80, 90, float('inf')], 
                                     labels=['AVSC1', 'AVSC2', 'ENG01', 'ENG02', 'ENG03', 'ENG04', 'ENG05']))

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\508205848.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['mamh'] = df4['mamh'].where(df4['mamh'] != 'NULL',

In [122]:
df4['mamh'].unique()

array(['AVSC1', 'AVSC2', 'ENG01', 'ENG02', 'ENG03', 'ENG05', 'ENG04',
       'Miễn ENG03'], dtype=object)

In [123]:
df4[df4["ghichu"]==" Qui đổi TOEIC"]

,id,mssv,listening,reading,total,mamh,ghichu
3379,3420.0,4784C672XPvAibaEXe9Tdz4CswjA16eg3cXIH7xa,47.0,69.0,630.0,ENG05,Qui đổi TOEIC
3380,3421.0,280F7F2EXPvAibaEXe/TOGeH6x1BlQUztAN4ABTM,45.0,68.0,610.0,Miễn ENG03,Qui đổi TOEIC
3381,3422.0,3A16B235XPvAibaEXe8NM1/5chXJmoMJkfAtL/mC,46.0,67.0,610.0,Miễn ENG03,Qui đổi TOEIC
3382,3423.0,0F92557CXPvAibaEXe9176253k6Mv7DsmZGZMkgF,45.0,67.0,605.0,Miễn ENG03,Qui đổi TOEIC
3383,3424.0,C6BEEDEBXPvAibaEXe/Hd2nFsMs4VJMEohtoTdvd,44.0,68.0,605.0,Miễn ENG03,Qui đổi TOEIC
...,...,...,...,...,...,...,...
4520,4560.0,4F5A9BB9XPvAibaEXe/bcCn8ANC28GDG/07C7RwI,13.0,29.0,230.0,AVSC1,Qui đổi TOEIC
4521,4561.0,F55BBDC5XPvAibaEXe9V50Ts4UAUsCMOge7bqzt+,14.0,28.0,230.0,AVSC1,Qui đổi TOEIC
4522,4562.0,ADB85DE2XPvAibaEXe+6gZchb6tvC8YoEtEdoGD9,13.0,29.0,230.0,AVSC1,Qui đổi TOEIC
4523,4563.0,80CDDDF4XPvAibaEXe8zi/ZLIzSiuMk6tTI8ZBuE,12.0,30.0,230.0,AVSC1,Qui đổi TOEIC
4524,4564.0,58162388XPvAibaEXe81fV8vPRwD6EDfDvQ2K8hC,16.0,26.0,230.0,AVSC1,Qui đổi TOEIC

##Lưu dữ liệu đã làm sạch

In [124]:
df4.to_csv('data_clean/04.xeploaiav.csv', index=False)

#Bang 05.ThiSinh.xlsx

##Xử lý chung

In [125]:
# Đọc dữ liệu
df5 = pd.read_excel("Education_dataset_V2/05.ThiSinh.xlsx")
df5.head()

,mssv,dien_tt,diem_tt,lop12_matinh,lop12_matruong,TEN_TRUONG
0,7E308531XPvAibaEXe879+AOg1gh8i58Q/VMq7RU,THPT,24.5,53.0,32.0,THPT Bình Đông
1,0FCB6532XPvAibaEXe879+AOg1gh8o0EEQcYQ8HR,THPT,27.5,16.0,41.0,THPT Lê Xoay
2,BAF446BFXPvAibaEXe879+AOg1gh8uQrEauqA0AG,THPT,25.0,42.0,21.0,THPT Di Linh
3,599DFFB8XPvAibaEXe879+AOg1gh8lJvChSN7o+V,THPT,28.0,51.0,34.0,THPT Mỹ Hiệp
4,364B9E9BXPvAibaEXe879+AOg1gh8sRVdBmZSiXe,THPT,24.5,52.0,39.0,TTGDTX-HN Đất Đỏ (Trước 01/7/2019)

In [126]:
# Bỏ khoảng trắng ở tên cột
df5.columns = df5.columns.str.strip()
df5.columns

Index(['mssv', 'dien_tt', 'diem_tt', 'lop12_matinh', 'lop12_matruong',
       'TEN_TRUONG'],
      dtype='object')

In [127]:
df5.drop(columns=["lop12_matruong", "TEN_TRUONG"], inplace=True)

In [128]:
df5["khuvuc"] = df5["lop12_matinh"].apply(lambda x: 1 if x==2 and not np.isnan(x)  
                                          else 0 if not np.isnan(x) 
                                          else np.nan)

In [129]:
df5

,mssv,dien_tt,diem_tt,lop12_matinh,khuvuc
0,7E308531XPvAibaEXe879+AOg1gh8i58Q/VMq7RU,THPT,24.50,53.0,0.0
1,0FCB6532XPvAibaEXe879+AOg1gh8o0EEQcYQ8HR,THPT,27.50,16.0,0.0
2,BAF446BFXPvAibaEXe879+AOg1gh8uQrEauqA0AG,THPT,25.00,42.0,0.0
3,599DFFB8XPvAibaEXe879+AOg1gh8lJvChSN7o+V,THPT,28.00,51.0,0.0
4,364B9E9BXPvAibaEXe879+AOg1gh8sRVdBmZSiXe,THPT,24.50,52.0,0.0
...,...,...,...,...,...
8229,418187C9XPvAibaEXe8Wb350a8ibnhbWI4z++VY2,THPT,21.10,56.0,0.0
8230,738946F2XPvAibaEXe8Wb350a8ibnm5kQzFjIM2p,THPT,23.95,37.0,0.0
8231,332E756EXPvAibaEXe8Wb350a8ibnvs4VyUWS40K,THPT,21.50,2.0,1.0
8232,AB431338XPvAibaEXe8xMCTZ03/BexWzDCyWVsT3,THPT,24.70,47.0,0.0
8233,75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM,THPT,24.95,42.0,0.0

In [130]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8234 entries, 0 to 8233
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mssv          8234 non-null   object
 1   dien_tt       8234 non-null   object
 2   diem_tt       8104 non-null   float64
 3   lop12_matinh  6060 non-null   float64
 4   khuvuc        6060 non-null   float64
dtypes: float64(3), object(2)
memory usage: 321.8+ KB

In [131]:
df5.isna().sum()

mssv               0
dien_tt            0
diem_tt          130
lop12_matinh    2174
khuvuc          2174
dtype: int64

###Xử lí khu vực (có ở TPHCM hay không)

In [132]:
df5["dien_tt"].unique()

array(['THPT', 'TT-Bộ', 'CUTUYEN', 'ƯT-Bộ', '30A', 'ƯT-ĐHQG', 'ĐGNL',
       'CCQT'], dtype=object)

In [133]:
df5.groupby("dien_tt").apply(lambda x: x.isna().sum())

         mssv  dien_tt  diem_tt  lop12_matinh  khuvuc
dien_tt
30A         0        0        1             2       2
CCQT        0        0        1             1       1
CUTUYEN     0        0       17            25      25
THPT        0        0        2          2027    2027
TT-Bộ       0        0       46            56      56
ĐGNL        0        0        0             0       0
ƯT-Bộ       0        0       15            15      15
ƯT-ĐHQG     0        0       48            48      48

In [134]:
# diện trúng tuyển là 30A thì khu vực là 0: ngoài TPHCM
df5["khuvuc"][df5["dien_tt"]=="30A"] = df5["khuvuc"][df5["dien_tt"]=="30A"].apply(lambda x: 0)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\940758150.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["khuvuc"][df5["dien_tt"]=="30A"] = df5["khuvuc"][df5["dien_tt"]=="30A"].apply(lambda x: 0)

In [135]:
# diện trúng tuyển là CCQT thì khu vực là 0: ngoài TPHCM
df5["khuvuc"][df5["dien_tt"]=="CCQT"] = df5["khuvuc"][df5["dien_tt"]=="CCQT"].apply(lambda x: 0)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\4030006960.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["khuvuc"][df5["dien_tt"]=="CCQT"] = df5["khuvuc"][df5["dien_tt"]=="CCQT"].apply(lambda x: 0)

In [136]:
# diện trúng tuyển là CỬ TUYỂN thì khu vực là 0: ngoài TPHCM, dân tộc thiểu số
df5["khuvuc"][df5["dien_tt"]=="CUTUYEN"] = df5["khuvuc"][df5["dien_tt"]=="CUTUYEN"].apply(lambda x: 0)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\2673047610.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["khuvuc"][df5["dien_tt"]=="CUTUYEN"] = df5["khuvuc"][df5["dien_tt"]=="CUTUYEN"].apply(lambda x: 0)

In [137]:
# diện trúng tuyển là THPT
mode_THPT = df5["khuvuc"][df5["dien_tt"]=="THPT"].mode()[0]
df5["khuvuc"][df5["dien_tt"]=="THPT"] = df5["khuvuc"][df5["dien_tt"]=="THPT"].fillna(mode_THPT)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\1016795327.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["khuvuc"][df5["dien_tt"]=="THPT"] = df5["khuvuc"][df5["dien_tt"]=="THPT"].fillna(mode_THPT)

In [138]:
# diện trúng tuyển là TT-Bộ thì khu vực là 0: ngoài TPHCM, dân tộc thiểu số
df5["khuvuc"][df5["dien_tt"]=="TT-Bộ"] = df5["khuvuc"][df5["dien_tt"]=="TT-Bộ"].apply(lambda x: 0)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\2137553221.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["khuvuc"][df5["dien_tt"]=="TT-Bộ"] = df5["khuvuc"][df5["dien_tt"]=="TT-Bộ"].apply(lambda x: 0)

In [139]:
df5["khuvuc"][df5["dien_tt"]=="ƯT-Bộ"] = df5["khuvuc"][df5["dien_tt"]=="ƯT-Bộ"].apply(lambda x: 0)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\3919060079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["khuvuc"][df5["dien_tt"]=="ƯT-Bộ"] = df5["khuvuc"][df5["dien_tt"]=="ƯT-Bộ"].apply(lambda x: 0)

In [140]:
# diện trúng tuyển là ƯT-ĐHQG
mode = df5["khuvuc"][df5["dien_tt"]=="ƯT-ĐHQG"].mode()[0]
df5["khuvuc"][df5["dien_tt"]=="ƯT-ĐHQG"] = df5["khuvuc"][df5["dien_tt"]=="ƯT-ĐHQG"].fillna(mode)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\3878641207.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["khuvuc"][df5["dien_tt"]=="ƯT-ĐHQG"] = df5["khuvuc"][df5["dien_tt"]=="ƯT-ĐHQG"].fillna(mode)

### Xử lí cột điểm, xếp loại

In [141]:
df5.groupby("dien_tt").apply(lambda x: x.isna().sum())

         mssv  dien_tt  diem_tt  lop12_matinh  khuvuc
dien_tt
30A         0        0        1             2       0
CCQT        0        0        1             1       0
CUTUYEN     0        0       17            25       0
THPT        0        0        2          2027       0
TT-Bộ       0        0       46            56       0
ĐGNL        0        0        0             0       0
ƯT-Bộ       0        0       15            15       0
ƯT-ĐHQG     0        0       48            48       0

In [142]:
df5["xl_tt"] = np.nan
df5

,mssv,dien_tt,diem_tt,lop12_matinh,khuvuc,xl_tt
0,7E308531XPvAibaEXe879+AOg1gh8i58Q/VMq7RU,THPT,24.50,53.0,0.0,NaN
1,0FCB6532XPvAibaEXe879+AOg1gh8o0EEQcYQ8HR,THPT,27.50,16.0,0.0,NaN
2,BAF446BFXPvAibaEXe879+AOg1gh8uQrEauqA0AG,THPT,25.00,42.0,0.0,NaN
3,599DFFB8XPvAibaEXe879+AOg1gh8lJvChSN7o+V,THPT,28.00,51.0,0.0,NaN
4,364B9E9BXPvAibaEXe879+AOg1gh8sRVdBmZSiXe,THPT,24.50,52.0,0.0,NaN
...,...,...,...,...,...,...
8229,418187C9XPvAibaEXe8Wb350a8ibnhbWI4z++VY2,THPT,21.10,56.0,0.0,NaN
8230,738946F2XPvAibaEXe8Wb350a8ibnm5kQzFjIM2p,THPT,23.95,37.0,0.0,NaN
8231,332E756EXPvAibaEXe8Wb350a8ibnvs4VyUWS40K,THPT,21.50,2.0,1.0,NaN
8232,AB431338XPvAibaEXe8xMCTZ03/BexWzDCyWVsT3,THPT,24.70,47.0,0.0,NaN
8233,75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM,THPT,24.95,42.0,0.0,NaN

In [143]:
# diện 30A
df5["xl_tt"][df5["dien_tt"]=="30A"] = df5["xl_tt"][df5["dien_tt"]=="30A"].apply(lambda x: 1)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\2722423363.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["xl_tt"][df5["dien_tt"]=="30A"] = df5["xl_tt"][df5["dien_tt"]=="30A"].apply(lambda x: 1)

In [144]:
# diện CCQT
df5["xl_tt"][df5["dien_tt"]=="CCQT"] = df5["xl_tt"][df5["dien_tt"]=="CCQT"].apply(lambda x: 4)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\3779447890.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["xl_tt"][df5["dien_tt"]=="CCQT"] = df5["xl_tt"][df5["dien_tt"]=="CCQT"].apply(lambda x: 4)

In [145]:
# diện CUTUYEN
df5["xl_tt"][df5["dien_tt"]=="CUTUYEN"] = df5["xl_tt"][df5["dien_tt"]=="CUTUYEN"].apply(lambda x: 1)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\1636230513.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["xl_tt"][df5["dien_tt"]=="CUTUYEN"] = df5["xl_tt"][df5["dien_tt"]=="CUTUYEN"].apply(lambda x: 1)

In [146]:
# diện TT-Bộ
df5["xl_tt"][df5["dien_tt"]=="TT-Bộ"] = df5["xl_tt"][df5["dien_tt"]=="TT-Bộ"].apply(lambda x: 4)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\2815734939.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["xl_tt"][df5["dien_tt"]=="TT-Bộ"] = df5["xl_tt"][df5["dien_tt"]=="TT-Bộ"].apply(lambda x: 4)

In [147]:
# diện ƯT-Bộ
df5["xl_tt"][df5["dien_tt"]=="ƯT-Bộ"] = df5["xl_tt"][df5["dien_tt"]=="ƯT-Bộ"].apply(lambda x: 4)

C:\Users\anhdu\AppData\Local\Temp\ipykernel_16184\3855499261.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["xl_tt"][df5["dien_tt"]=="ƯT-Bộ"] = df5["xl_tt"][df5["dien_tt"]=="ƯT-Bộ"].apply(lambda x: 4)

In [148]:
#Kiểm tra trùng lặp
df5.duplicated().sum()

0

In [149]:
df5.to_csv('data_clean/05.ThiSinh.csv', index=False)

#Bảng 6. XLHV

##Xử lý chung

In [150]:
# Đọc dữ liệu
df6 = pd.read_excel("Education_dataset_V2/08.XLHV.xlsx")
df6.head()

,id,mssv,tinhtrang,lydo,hocky,namhoc,soqd,ngayqd,Column1
0,7595.0,98247E19XPvAibaEXe93PEySAJOVkxsz+HIviyYJ,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,189/QĐ-ĐHCNTT,2017-04-18,NaN
1,7596.0,52B1CC2DXPvAibaEXe+kwIr/VXjl0w+FyuW1abQ7,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,189/QĐ-ĐHCNTT,2017-04-18,NaN
2,7597.0,5666EAF4XPvAibaEXe+Z7KfNHYLttJaLI+SH+DpO,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,189/QĐ-ĐHCNTT,2017-04-18,NaN
3,7598.0,682C32E0XPvAibaEXe/Bn5cQSu92WX0DcIKdud8D,2.0,Bị cảnh cáo vì ĐTB 2 học kỳ liên tiếp < 4,2.0,2016.0,189/QĐ-ĐHCNTT,2017-04-18,NaN
4,7599.0,7901D3A9XPvAibaEXe+6MN9FoW2mqYEmruXXBNsS,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,189/QĐ-ĐHCNTT,2017-04-18,NaN

In [151]:
# Bỏ khoảng trắng ở tên cột
df6.columns = df6.columns.str.strip()
df6.columns

Index(['id', 'mssv', 'tinhtrang', 'lydo', 'hocky', 'namhoc', 'soqd', 'ngayqd',
       'Column1'],
      dtype='object')

In [152]:
df6.isnull().sum()

id              7
mssv            7
tinhtrang       7
lydo            7
hocky         826
namhoc          7
soqd            7
ngayqd       1772
Column1      2633
dtype: int64

In [153]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3452 entries, 0 to 3451
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         3445 non-null   float64
 1   mssv       3445 non-null   object
 2   tinhtrang  3445 non-null   float64
 3   lydo       3445 non-null   object
 4   hocky      2626 non-null   float64
 5   namhoc     3445 non-null   float64
 6   soqd       3445 non-null   object
 7   ngayqd     1680 non-null   datetime64[ns]
 8   Column1    819 non-null    object
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 242.8+ KB

##hocky

In [154]:
#Xử lý các giá trị còn thiếu trong cột hocky
df6['hocky'].fillna(df6['namhoc'], inplace=True)

In [155]:
df6.isnull().sum()

id              7
mssv            7
tinhtrang       7
lydo            7
hocky           7
namhoc          7
soqd            7
ngayqd       1772
Column1      2633
dtype: int64

In [156]:
#Xoá hai cột ngayqd và Column1
df6.drop(columns=['ngayqd', 'Column1'], inplace=True)

In [157]:
#Xoá các giá trị NaN trong bảng
df6.dropna(inplace=True)

In [158]:
df6.isnull().sum()

id           0
mssv         0
tinhtrang    0
lydo         0
hocky        0
namhoc       0
soqd         0
dtype: int64

##Lưu dữ liệu đã được làm sạch

In [159]:
df6.to_csv('data_clean/06.XLHV.csv', index=False)

#Bảng 7. diemrl

### Xử lí chung

In [160]:
# Đọc dữ liệu
df7_1 = pd.read_excel("Education_dataset_V2/10.diemrl.xlsx")
df7_1.head()

,id,mssv,lopsh,hocky,namhoc,drl,ghichu
0,27.0,599DFFB8XPvAibaEXe879+AOg1gh8lJvChSN7o+V,ANTN2013,2.0,2013.0,59.0,NULL
1,28.0,FC77E598XPvAibaEXe879+AOg1gh8pb/q8KzJ2A3,ANTN2013,2.0,2013.0,91.0,NULL
2,29.0,51E1C3E0XPvAibaEXe+4hxKfaQWuhLp2zzmiiyRe,ANTN2013,2.0,2013.0,93.0,NULL
3,30.0,6920B9AAXPvAibaEXe83EtiN4MI2ns6NZhlUAIhE,ANTN2013,2.0,2013.0,69.0,NULL
4,31.0,2F237AA9XPvAibaEXe/YKAlYnC3m967dOM4WK2IJ,ANTN2013,2.0,2013.0,72.0,NULL

In [161]:
# Đọc dữ liệu từ bảng 2
df7_2 = pd.read_excel("Education_dataset_V2/diemrl.xlsx")
df7_2.head()

,id,mssv,lopsh,hocky,namhoc,drl,ghichu
0,1,2A10C466XPvAibaEXe8vcQUX+A6FeNIl5Loug1zV,ANTN2012,2,2013,81,NaN
1,2,903ADF1AXPvAibaEXe9p5G9u2qRxxZEjiJjD4Ztl,ANTN2012,2,2013,88,NaN
2,3,F06EDFFEXPvAibaEXe8KSegZW1rFPMNPBQ+c9rst,ANTN2012,2,2013,94,NaN
3,4,AA868AD5XPvAibaEXe+1Gm1QkI5oNyTYwjwmgxhx,ANTN2012,2,2013,86,NaN
4,5,E7105148XPvAibaEXe+E7LJdSZ9AW2sUcg4OSCnU,ANTN2012,2,2013,88,NaN

In [162]:
# Xử lí khoảng trắng ở tên cột
df7_1.columns = df7_1.columns.str.strip()
df7_2.columns = df7_2.columns.str.strip()
df7_1.columns

Index(['id', 'mssv', 'lopsh', 'hocky', 'namhoc', 'drl', 'ghichu'], dtype='object')

In [163]:
df7_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54057 entries, 0 to 54056
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20000 non-null  float64
 1   mssv    54001 non-null  object
 2   lopsh   54001 non-null  object
 3   hocky   54001 non-null  float64
 4   namhoc  54001 non-null  float64
 5   drl     3333 non-null   float64
 6   ghichu  54001 non-null  object
dtypes: float64(4), object(3)
memory usage: 2.9+ MB

In [164]:
df7_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111978 entries, 0 to 111977
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      111978 non-null  int64
 1   mssv    111978 non-null  object
 2   lopsh   101450 non-null  object
 3   hocky   111978 non-null  int64
 4   namhoc  111978 non-null  int64
 5   drl     111978 non-null  int64
 6   ghichu  14768 non-null   object
dtypes: int64(4), object(3)
memory usage: 6.0+ MB

In [165]:
df7_1.isna().sum()

id        34057
mssv         56
lopsh        56
hocky        56
namhoc       56
drl       50724
ghichu       56
dtype: int64

In [166]:
df7_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111978 entries, 0 to 111977
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      111978 non-null  int64
 1   mssv    111978 non-null  object
 2   lopsh   101450 non-null  object
 3   hocky   111978 non-null  int64
 4   namhoc  111978 non-null  int64
 5   drl     111978 non-null  int64
 6   ghichu  14768 non-null   object
dtypes: int64(4), object(3)
memory usage: 6.0+ MB

In [167]:
#Nối hai bảng dữ liệu với nhau
df7 = pd.merge(df7_1, df7_2, on='mssv', how='outer')
df7.head()

,id_x,mssv,lopsh_x,hocky_x,namhoc_x,drl_x,ghichu_x,id_y,lopsh_y,hocky_y,namhoc_y,drl_y,ghichu_y
0,27.0,599DFFB8XPvAibaEXe879+AOg1gh8lJvChSN7o+V,ANTN2013,2.0,2013.0,59.0,NULL,27.0,ANTN2013,2.0,2013.0,59.0,NaN
1,27.0,599DFFB8XPvAibaEXe879+AOg1gh8lJvChSN7o+V,ANTN2013,2.0,2013.0,59.0,NULL,19238.0,ANTN2013,1.0,2014.0,43.0,NaN
2,27.0,599DFFB8XPvAibaEXe879+AOg1gh8lJvChSN7o+V,ANTN2013,2.0,2013.0,59.0,NULL,26181.0,KTPM2013,2.0,2014.0,24.0,NaN
3,27.0,599DFFB8XPvAibaEXe879+AOg1gh8lJvChSN7o+V,ANTN2013,2.0,2013.0,59.0,NULL,37829.0,KTPM2013,1.0,2015.0,69.0,NaN
4,27.0,599DFFB8XPvAibaEXe879+AOg1gh8lJvChSN7o+V,ANTN2013,2.0,2013.0,59.0,NULL,49363.0,KTPM2013,2.0,2015.0,52.0,NaN

In [168]:
#Xoá cột ghichu_y
df7.drop(columns=['ghichu_y'], inplace=True)

In [169]:
df7.isna().sum()

id_x        360670
mssv            56
lopsh_x      42900
hocky_x      42900
namhoc_x     42900
drl_x       521752
ghichu_x     42900
id_y            56
lopsh_y      18228
hocky_y         56
namhoc_y        56
drl_y           56
dtype: int64

In [170]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 552830 entries, 0 to 552829
Data columns (total 12 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id_x      192160 non-null  float64
 1   mssv      552774 non-null  object
 2   lopsh_x   509930 non-null  object
 3   hocky_x   509930 non-null  float64
 4   namhoc_x  509930 non-null  float64
 5   drl_x     31078 non-null   float64
 6   ghichu_x  509930 non-null  object
 7   id_y      552774 non-null  float64
 8   lopsh_y   534602 non-null  object
 9   hocky_y   552774 non-null  float64
 10  namhoc_y  552774 non-null  float64
 11  drl_y     552774 non-null  float64
dtypes: float64(8), object(4)
memory usage: 54.8+ MB

In [171]:
#xoá những hàng có giá trị NaN
df7 =df7.dropna()
df7.isna().sum()

id_x        0
mssv        0
lopsh_x     0
hocky_x     0
namhoc_x    0
drl_x       0
ghichu_x    0
id_y        0
lopsh_y     0
hocky_y     0
namhoc_y    0
drl_y       0
dtype: int64

##Lưu dữ liệu đã làm sạch

In [172]:
df7.to_csv('data_clean/07.diemrl.csv', index=False)

#Bảng 8. baoluu

### Xử lí chung

In [173]:
# Đọc dữ liệu
df8 = pd.read_excel("Education_dataset_V2/12.baoluu.xlsx")
df8.head()

,id,masv,tinhtrang,lydo,hocky,namhoc,soqd,ngayqd
0,7532.0,E95E7C6DXPvAibaEXe+1j/AqdkpM22DHf6P99fDJ,3.0,TN,2.0,2016.0,178 /QĐ-ĐHCNTT,2017-04-14
1,8304.0,EBC8A649XPvAibaEXe+fmxcqgvribIboSP1ToKmG,3.0,,1.0,2017.0,713/QD-DHCNTT,2017-10-06
2,8305.0,2ABBE719XPvAibaEXe9hPQQhQOOPyUJ9WJU9hlCM,3.0,,1.0,2017.0,713/QD-DHCNTT,2017-10-06
3,8306.0,C307F053XPvAibaEXe+nZBq3b0XEhX8PABYu6iV1,3.0,,1.0,2017.0,713/QD-DHCNTT,2017-10-06
4,8307.0,F99CE6DEXPvAibaEXe86736b6Ol+/O3ZQU1AW1/C,3.0,,1.0,2017.0,713/QD-DHCNTT,2017-10-06

In [174]:
df8.columns

Index(['id', ' masv', ' tinhtrang', ' lydo', ' hocky', ' namhoc', ' soqd',
       ' ngayqd'],
      dtype='object')

In [175]:
df8.columns = df8.columns.str.strip()
df8.columns

Index(['id', 'masv', 'tinhtrang', 'lydo', 'hocky', 'namhoc', 'soqd', 'ngayqd'], dtype='object')

In [176]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1880 entries, 0 to 1879
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1878 non-null   float64
 1   masv       1878 non-null   object
 2   tinhtrang  1878 non-null   float64
 3   lydo       1878 non-null   object
 4   hocky      1878 non-null   float64
 5   namhoc     1878 non-null   float64
 6   soqd       1878 non-null   object
 7   ngayqd     1878 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(4), object(3)
memory usage: 117.6+ KB

In [177]:
df8.isna().sum()

id           2
masv         2
tinhtrang    2
lydo         2
hocky        2
namhoc       2
soqd         2
ngayqd       2
dtype: int64

In [178]:
df8.dropna(inplace=True)

###lydo

In [179]:
df8["lydo"].unique()

array([' TN', ' ',
       ' Chứng chỉ Anh văn không đạt --> CNTN tốt nghiệp chuyển sang hệ CQĐT',
       ' QĐ điều chỉnh ngành TN', ' Tốt nghiệp'], dtype=object)

In [180]:
df8["lydo"] = df8["lydo"].str.strip()

###soqd

In [181]:
df8["soqd"].unique()

array([' 178 /QĐ-ĐHCNTT', ' 713/QD-DHCNTT', ' 713/QĐ-ĐHCNTT',
       ' 823/QĐ_ĐHCNTT', ' 772/QĐ_ĐHCNTT', ' 66 /QĐ-ĐHCNTT',
       ' 222/QĐ-ĐHCNTT', ' 233/QĐ-ĐHCNTT', ' 249/QĐ-ĐHCNTT',
       ' 243/QĐ-ĐHCNTT', ' 384/QĐ-ĐHCNTT', ' 621/QĐ-ĐHCNTT',
       ' 829/QĐ-ĐHCNTT', ' 204 /QĐ-ĐHCNTT', '236', '258',
       ' 298 /QĐ-ĐHCNTT', '306', ' 341 /QĐ-ĐHCNTT', ' 344 /QĐ-ĐHCNTT',
       ' 13/QĐ-ĐHCNTT', ' 443/QĐ-ĐHCNTT', ' 519/QĐ-ĐHCNTT',
       ' 675/QĐ-ĐHCNTT', ' 733/QĐ-ĐHCNTT', ' 761/QĐ-ĐHCNTT',
       ' 811/QĐ-ĐHCNTT', ' 852 /QĐ-ĐHCNTT', ' 960/QĐ-ĐHCNTT',
       ' 214/QĐ-ĐHCNTT', ' 242/QĐ-ĐHCNTT', ' 239/QĐ-ĐHCNTT',
       ' 320/QĐ-ĐHCNTT', ' 310/QĐ-ĐHCNTT', ' 325/QĐ-ĐHCNTT',
       ' 370/QĐ-ĐHCNTT', ' 391/QĐ-ĐHCNTT', ' 430/QĐ-ĐHCNTT',
       ' 542/QĐ-ĐHCNTT', ' 595/QĐ-ĐHCNTT', ' 777/QĐ-ĐHCNTT',
       ' 878/QĐ-ĐHCNTT', ' 955/QĐ-ĐHCNTT', ' 189/QĐ-ĐHCNTT',
       ' 354 /QĐ-ĐHCNTT'], dtype=object)

In [182]:
df8["soqd"] = df8["soqd"].str.strip()

### Lưu dữ liệu đã được làm sạch

In [183]:
df8.to_csv('data_clean/12.baoluu.csv', index=False)

#Bảng 9. totnghiep

###Xử lí chung

In [184]:
# Đọc dữ liệu
df9 = pd.read_excel("Education_dataset_V2/14.totnghiep.xlsx")
df9.head()

,id,mssv,xeploai,soquyetdinh,ngaycapvb
0,76328.0,E95E7C6DXPvAibaEXe+1j/AqdkpM22DHf6P99fDJ,Khá,178/QĐ_ĐHCNTT,14/04/2017
1,76663.0,D0FE4969XPvAibaEXe/yXiKgsgy0slCmJ5EKt6Ki,Giỏi,713/QĐ_ĐHCNTT,06/10/2017
2,76664.0,40F7E8D0XPvAibaEXe+nZBq3b0XEhfcwXLmoc4Pj,Giỏi,713/QĐ_ĐHCNTT,06/10/2017
3,76665.0,0A049F45XPvAibaEXe9CtFSNMbfIz9qE7i0Fu4My,Khá,713/QĐ_ĐHCNTT,06/10/2017
4,76666.0,7A7166DAXPvAibaEXe83V/kFvw2bBZ0o/KVHZc30,Khá,713/QĐ_ĐHCNTT,06/10/2017

In [185]:
# In ra các cột của bảng
df9.columns

Index(['id', 'mssv', ' xeploai', ' soquyetdinh', ' ngaycapvb'], dtype='object')

In [186]:
# Bỏ khoảng trắng ở tên cột
df9.columns = df9.columns.str.strip()
df9.columns

Index(['id', 'mssv', 'xeploai', 'soquyetdinh', 'ngaycapvb'], dtype='object')

In [187]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1847 entries, 0 to 1846
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           1845 non-null   float64
 1   mssv         1845 non-null   object
 2   xeploai      1845 non-null   object
 3   soquyetdinh  1845 non-null   object
 4   ngaycapvb    1845 non-null   object
dtypes: float64(1), object(4)
memory usage: 72.3+ KB

In [188]:
df9.isna().sum()

id             2
mssv           2
xeploai        2
soquyetdinh    2
ngaycapvb      2
dtype: int64

In [189]:
df9.dropna(inplace=True)

###xeploai

In [190]:
df9["xeploai"].unique()

array([' Khá', ' Giỏi', ' Trung bình khá', ' Xuất sắc', ' Trung bình Khá',
       ' TB Khá', ' TB khá'], dtype=object)

In [191]:
df9["xeploai"] = df9["xeploai"].str.strip()
df9["xeploai"].unique()

array(['Khá', 'Giỏi', 'Trung bình khá', 'Xuất sắc', 'Trung bình Khá',
       'TB Khá', 'TB khá'], dtype=object)

In [192]:
df9['xeploai'].replace(['Trung bình Khá', 'TB Khá', 'TB khá'], 'Trung bình khá', inplace=True)
df9['xeploai'].unique()

array(['Khá', 'Giỏi', 'Trung bình khá', 'Xuất sắc'], dtype=object)

###soquyetdinh

In [193]:
df9["soquyetdinh"].unique()

array([' 178/QĐ_ĐHCNTT', ' 713/QĐ_ĐHCNTT', ' 772/QĐ_ĐHCNTT',
       ' 823/QĐ_ĐHCNTT', ' 66/QĐ_ĐHCNTT', ' 222/QĐ-ĐHCNTT',
       ' 233/QĐ-ĐHCNTT', ' 249/QĐ-ĐHCNTT', ' 384/QĐ-ĐHCNTT',
       ' 621/QĐ-ĐHCNTT', ' 829/QĐ-ĐHCNTT', ' 13/QĐ-ĐHCNTT',
       ' 204/QĐ-ĐHCNTT', ' 236/QĐ-ĐHCNTT', ' 258/QĐ-ĐHCNTT',
       ' 298/QĐ-ĐHCNTT', ' 306/QĐ-ĐHCNTT', ' 341/QĐ-ĐHCNTT',
       ' 344/QĐ-ĐHCNTT', ' 443-QD-DHCNTT', ' 519-QD-DHCNTT',
       ' 675/QĐ-ĐHCNTT', ' 761/QĐ-ĐHCNTT', ' 733/QĐ-ĐHCNTT',
       ' 811/QĐ-ĐHCNTT', ' 852/QĐ-ĐHCNTT', ' 960/QĐ-ĐHCNTT',
       ' 214/QĐ_ĐHCNTT', ' 242/QĐ_ĐHCNTT', ' 239/QĐ_ĐHCNTT',
       ' 320/QĐ_ĐHCNTT', ' 310/QĐ_ĐHCNTT', ' 325/QĐ_ĐHCNTT',
       ' 370/QĐ_ĐHCNTT', ' 391/QĐ_ĐHCNTT', ' 430/QĐ_ĐHCNTT',
       ' 542/QĐ_ĐHCNTT', ' 595/QĐ_ĐHCNTT', ' 777/QĐ-ĐHCNTT',
       ' 878/QĐ-ĐHCNTT', ' 955/QĐ-ĐHCNTT', ' 189/QĐ-ĐHCNTT',
       ' 354/QĐ-ĐHCNTT'], dtype=object)

In [194]:
df9["soquyetdinh"] = df9["soquyetdinh"].str.strip()
df9["soquyetdinh"].unique()

array(['178/QĐ_ĐHCNTT', '713/QĐ_ĐHCNTT', '772/QĐ_ĐHCNTT', '823/QĐ_ĐHCNTT',
       '66/QĐ_ĐHCNTT', '222/QĐ-ĐHCNTT', '233/QĐ-ĐHCNTT', '249/QĐ-ĐHCNTT',
       '384/QĐ-ĐHCNTT', '621/QĐ-ĐHCNTT', '829/QĐ-ĐHCNTT', '13/QĐ-ĐHCNTT',
       '204/QĐ-ĐHCNTT', '236/QĐ-ĐHCNTT', '258/QĐ-ĐHCNTT', '298/QĐ-ĐHCNTT',
       '306/QĐ-ĐHCNTT', '341/QĐ-ĐHCNTT', '344/QĐ-ĐHCNTT', '443-QD-DHCNTT',
       '519-QD-DHCNTT', '675/QĐ-ĐHCNTT', '761/QĐ-ĐHCNTT', '733/QĐ-ĐHCNTT',
       '811/QĐ-ĐHCNTT', '852/QĐ-ĐHCNTT', '960/QĐ-ĐHCNTT', '214/QĐ_ĐHCNTT',
       '242/QĐ_ĐHCNTT', '239/QĐ_ĐHCNTT', '320/QĐ_ĐHCNTT', '310/QĐ_ĐHCNTT',
       '325/QĐ_ĐHCNTT', '370/QĐ_ĐHCNTT', '391/QĐ_ĐHCNTT', '430/QĐ_ĐHCNTT',
       '542/QĐ_ĐHCNTT', '595/QĐ_ĐHCNTT', '777/QĐ-ĐHCNTT', '878/QĐ-ĐHCNTT',
       '955/QĐ-ĐHCNTT', '189/QĐ-ĐHCNTT', '354/QĐ-ĐHCNTT'], dtype=object)

###ngaycapvb

In [195]:
df9["ngaycapvb"].unique()

array([' 14/04/2017', ' 06/10/2017', ' 07/11/2017', ' 21/11/2017',
       ' 19/01/2018', ' 10/04/2018', ' 16/04/2018', ' 26/04/2018',
       ' 03/07/2018', ' 10/10/2018', ' 06/12/2018', ' 10/01/2019',
       ' 12/04/2019', ' 02/05/2019', ' 10/05/2019', ' 23/05/2019',
       ' 29/05/2019', ' 05/06/2019', ' 10/06/2019', ' 01/08/2019',
       ' 26/08/2019', ' 11/10/2019', ' 11/10/2019);', ' 05/11/2019',
       ' 28/10/2019', ' 22/11/2019', ' 02/12/2019', ' 31/12/2019',
       ' 18/05/2020', ' 27-5-2020', ' 26/05/2020', ' 17/06/2020',
       ' 15/06/2020', ' 19/06/2020', ' 07/07/2020', ' 16/07/2020',
       ' 31/07/2020', ' 31/08/2020', ' 24/09/2020', ' 12/11/2020',
       ' 07/12/2020', ' 30/12/2020', ' 04/01/2021', ' 09/6/2021',
       ' 09/6/2021);'], dtype=object)

In [196]:
df9["ngaycapvb"] = df9["ngaycapvb"].str.strip()
df9["ngaycapvb"].unique()

array(['14/04/2017', '06/10/2017', '07/11/2017', '21/11/2017',
       '19/01/2018', '10/04/2018', '16/04/2018', '26/04/2018',
       '03/07/2018', '10/10/2018', '06/12/2018', '10/01/2019',
       '12/04/2019', '02/05/2019', '10/05/2019', '23/05/2019',
       '29/05/2019', '05/06/2019', '10/06/2019', '01/08/2019',
       '26/08/2019', '11/10/2019', '11/10/2019);', '05/11/2019',
       '28/10/2019', '22/11/2019', '02/12/2019', '31/12/2019',
       '18/05/2020', '27-5-2020', '26/05/2020', '17/06/2020',
       '15/06/2020', '19/06/2020', '07/07/2020', '16/07/2020',
       '31/07/2020', '31/08/2020', '24/09/2020', '12/11/2020',
       '07/12/2020', '30/12/2020', '04/01/2021', '09/6/2021',
       '09/6/2021);'], dtype=object)

### Lưu dữ liệu đã làm sạch

In [197]:
df9.to_csv('data_clean/14.totnghiep.csv', index=False)

#Bảng 10. diem_Thu

In [198]:
# Đọc dữ liệu
df10 = pd.read_excel("Education_dataset_V2/diem_Thu.xlsx")
df10.head()

,mssv,mamh,malop,sotc,hocky,namhoc,diem_qt,diem_th,diem_gk,diem_ck,diem_hp,trangthai,tinhtrang,mamh_tt
0,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,CARC1,K1C1_2,3,1,2006,NaN,NaN,NaN,NaN,2.0,2,0,NaN
1,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,CSC21,K1C1_2,5,1,2006,NaN,NaN,NaN,NaN,5.0,1,0,NaN
2,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,ENG02,K1C1_2,0,1,2006,NaN,NaN,NaN,NaN,5.5,1,0,NaN
3,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,MAT21,K1C1_2,4,1,2006,NaN,NaN,NaN,NaN,6.5,1,0,NaN
4,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,PEDU1,K1C1_2,0,1,2006,NaN,NaN,NaN,NaN,7.0,1,0,NaN

In [199]:
# In ra các cột của bảng
df10.columns

Index(['mssv', 'mamh', 'malop', 'sotc', 'hocky', 'namhoc', 'diem_qt',
       'diem_th', 'diem_gk', 'diem_ck', 'diem_hp', 'trangthai', 'tinhtrang',
       'mamh_tt'],
      dtype='object')

In [200]:
df10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674273 entries, 0 to 674272
Data columns (total 14 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   mssv       674273 non-null  object
 1   mamh       674273 non-null  object
 2   malop      674258 non-null  object
 3   sotc       674273 non-null  int64
 4   hocky      674273 non-null  int64
 5   namhoc     674273 non-null  int64
 6   diem_qt    297601 non-null  float64
 7   diem_th    238559 non-null  float64
 8   diem_gk    303975 non-null  float64
 9   diem_ck    513427 non-null  float64
 10  diem_hp    673659 non-null  float64
 11  trangthai  674273 non-null  int64
 12  tinhtrang  674273 non-null  int64
 13  mamh_tt    2741 non-null    object
dtypes: float64(5), int64(5), object(4)
memory usage: 72.0+ MB

In [201]:
# Thống kê giá trị NaN ở mỗi cột
df10.isna().sum()

mssv              0
mamh              0
malop            15
sotc              0
hocky             0
namhoc            0
diem_qt      376672
diem_th      435714
diem_gk      370298
diem_ck      160846
diem_hp         614
trangthai         0
tinhtrang         0
mamh_tt      671532
dtype: int64

In [202]:
df10["mamh_tt"].unique()

array([nan, 'NT113', 'CE115', 'IS202', 'CS108', 'SE104', 'CS109', 'ENG13',
       'ENG11', 'PHIL1', 'STAT11', 'MAT11', 'OOPT1', 'DSAL1', 'NT304',
       'PH001', 'MAT02', 'ENG01', 'SS001', 'ENG12', 'CSC12', 'PEDU2',
       'IT003', 'MA003', 'ENG03', 'CS104', 'CS102', 'CNET1', 'CS101',
       'CS322', 'CS103', 'NT101', 'CARC1', 'CSC01', 'DBSS1', 'IS204',
       'MAT04', 'LIA01', 'MAT01', 'STA01', 'ENG02', 'LIA11', 'PEDU1',
       'OSYS1', 'WINP1', 'ITEW1', 'IS103', 'IS102', 'ENG15', 'IS4263',
       'VCPL1', 'HCMT1', 'IT008', 'NT110', 'PHY01', 'IS104', 'IS206',
       'CE102', 'PHY02', 'IS501', 'CE202', 'SE212', 'SE341', 'SE311',
       'SE213', 'IS107', 'IS311', 'IS106', 'SE210', 'CS217', 'CE106',
       'CE109', 'PE001', 'SE103', 'NT301', 'IS205', 'SE209', 'NT202',
       'NT201', 'SE207', 'CE113', 'NT102', 'CE302', 'CE110', 'NT305',
       'SE322', 'NT321', 'NT302', 'SE321', 'SE211', 'SE208', 'NT203',
       'SE417', 'SE418', 'NT108', 'CE116', 'CE112', 'SS005', 'EN005',
       'NT107', 'NT403', 'EN003', 'EN002', 'NT116', 'SE107', 'SE337',
       'NT501', 'CS105', 'SE312', 'NT112', 'NT307', 'NT502', 'NT103',
       'CE219', 'NT503', 'NT504', 'IS212', 'PH003', 'MA001', 'IS253',
       'MA002', 'CE101', 'EN006', 'EN004', 'CS3363', 'IT006', 'CE104',
       'CS4793', 'IE209', 'NT130', 'CS3373', 'SS002', 'SE111', 'CS110',
       'IT012', 'CE107', 'EC212', 'NT115', 'IT009', 'CE221', 'SE108',
       'SE112', 'EC203', 'PE002', 'EC202'], dtype=object)

In [203]:
df10.to_csv('data_clean/diem_Thu.csv', index=False)

#Bảng 11. sinhvien_dtb_hocky

In [204]:
# Đọc dữ liệu
df11 = pd.read_excel("Education_dataset_V2/sinhvien_dtb_hocky.xlsx")
df11.head()

                                       mssv  hocky  namhoc  dtbhk  sotchk
0  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2016   6.45      13
1  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2016   5.86      17
2  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2017   6.54      16
3  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2017   5.67      23
4  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2018   2.27      21

In [205]:
# In ra các cột của bảng
df11.columns

Index(['mssv', 'hocky', 'namhoc', 'dtbhk', 'sotchk'], dtype='object')

In [206]:
df11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84952 entries, 0 to 84951
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mssv    84952 non-null  object
 1   hocky   84952 non-null  int64
 2   namhoc  84952 non-null  int64
 3   dtbhk   84952 non-null  float64
 4   sotchk  84952 non-null  int64
dtypes: float64(1), int64(3), object(1)
memory usage: 3.2+ MB

In [207]:
# Thống kê giá trị NaN ở mỗi cột
df11.isna().sum()

mssv      0
hocky     0
namhoc    0
dtbhk     0
sotchk    0
dtype: int64

In [208]:
# Có các giá trị outliers: số tín chỉ học kỳ
df11["sotchk"].unique()

array([ 13,  17,  16,  23,  21,  12,   6,  20,  15,   8,  19,  18,  24,
        22,   4,   7,   0,  11,  14,   3,  10,   5,  27,  25,  28,  26,
         9,   2,  29,  30,  32,  44,   1, 138, 195,  69, 192], dtype=int64)

In [209]:
df11.to_csv('data_clean/sinhvien_dtb_hocky.csv', index=False)

#Bảng 12. sinhvien_dtb_toankhoa

In [210]:
# Đọc dữ liệu
df12 = pd.read_excel("Education_dataset_V2/sinhvien_dtb_toankhoa.xlsx")
df12.head()

,mssv,dtb_toankhoa,dtb_tichluy,sotc_tichluy
0,C410FEC4XPvAibaEXe/odi52as1TQ/z6UAtEIyTx,7.00,7.00,144.0
1,4555C74CXPvAibaEXe8UBGVVSBKSkjQKdKZAX7FE,6.34,6.34,153.0
2,6FB8C971XPvAibaEXe8zjuWfAVBr9Syz83phZPbU,2.31,0.00,0.0
3,7D7299A4XPvAibaEXe9hYalhCsDQbVspsqAf44vo,8.21,8.21,148.0
4,590263C4XPvAibaEXe9mDsFtgVHJ/lr5wIkYTfyo,8.32,8.32,148.0

In [211]:
# In ra các cột của bảng
df12.columns

Index(['mssv', 'dtb_toankhoa', 'dtb_tichluy', 'sotc_tichluy'], dtype='object')

In [212]:
df12.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13970 entries, 0 to 13969
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mssv          13970 non-null  object
 1   dtb_toankhoa  13648 non-null  float64
 2   dtb_tichluy   13648 non-null  float64
 3   sotc_tichluy  13648 non-null  float64
dtypes: float64(3), object(1)
memory usage: 436.7+ KB

In [213]:
# Thống kê giá trị NaN ở mỗi cột
df12.isna().sum()

mssv              0
dtb_toankhoa    322
dtb_tichluy     322
sotc_tichluy    322
dtype: int64

In [214]:
# Loại bỏ các hàng có giá trị NaN
df12.dropna(inplace=True)
df12.shape

(13648, 4)

In [215]:
df12.to_csv('data_clean/sinhvien_dtb_toankhoa.csv', index=False)